### ISSUE TITLE
Cluster status is wrong when shards are initialising or relocating

### ISSUE THREAD

**Issue by elentar** [mobz/elasticsearch-head#147]
On 0.90.13, with the latest version of elasticsearch-head, clusters status is incorrect.

Cluster health:

{
cluster_name: logstash
status: yellow
timed_out: false
number_of_nodes: 13
number_of_data_nodes: 13
active_primary_shards: 80
active_shards: 159
relocating_shards: 2
initializing_shards: 1
unassigned_shards: 0
}

GUI display:

logstashcluster health: green (160 of 160)

**Comment by jbbarth** [comment]
I'd really like this to be solved as it is counter-intuitive when you're in a hard recovery situation. I opened a PR here: #185 with a first atttempt that works well for me. Any comment welcome!

**Comment by runningman84** [comment]
+1
