### ISSUE TITLE
ES Head is not working with elasticsearch-1.4.0.Beta1

### ISSUE THREAD

**Issue by sumit-gupta-sgt** [mobz/elasticsearch-head#170]
Hi,

ES Head is not working with elasticsearch-1.4.0.Beta1.Any body facing same issue.

Thanks,
Sumit

**Comment by hisuwh** [comment]
Running ES 1.4.2 and head seems to be very flaky.  It doesn't update on pressing the refresh button or refreshing the browser page.  I have to close the browser and re-open to get updates

The "Browser" tab of head doesn't actually show body of documents

The "Any Request" tab doesn't show the response from the server (though the requests seem to work)
