### ISSUE TITLE
cluster health: not connected Elasticsearch head unable to connect to Cluster

### ISSUE THREAD

**Issue by manjunathcbhat** [mobz/elasticsearch-head#189]
Hi All,
I am new to ES and learning the things/
I have downloaded ES and installed on Windows. I have also installed as Service and service is started.
WHen I say http://localhost:9200/ in my browser i get below OP

{
  "status" : 200,
  "name" : "Black Marvel",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.4.2",
    "build_hash" : "927caff6f05403e936c20bf4529f144f0c89fd8c",
    "build_timestamp" : "2014-12-16T14:11:12Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.2"
  },
  "tagline" : "You Know, for Search"
}

http://localhost:9200/_cluster/health?pretty=true
{
  "cluster_name" : "elasticsearch",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 1,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 0,
  "active_shards" : 0,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0
}

For Head plugin, I am unable to Install as because of my company plicy.
So I downloaded Zip file and Placed it in my Tomcat WebApp folder and when i say http://localhost:8080/EShead/
The head GUI open but below is the screen shot

![image](https://cloud.githubusercontent.com/assets/11421351/6593413/875d05e6-c7fe-11e4-8161-0f54d1b5dd69.png)

I am not sure what is wrong. Any help appreciated. thank you

**Comment by mobz** [comment]
Your browser is most likely blocking requests due to CORS

this is not an issue

**Comment by manjunathcbhat** [comment]
Hello,

Thank you.  Could you please let me know how can I check this and how can
make my browser not to block cors

**Comment by mobz** [comment]
There is plenty of information on networking and browser security on the internet. This is not the correct place for support.

**Comment by manjunathcbhat** [comment]
Thanks a Ton Sir. Yes it was CORS. I started by chrome disabling web security and enabling cors. Now I am able to see all well. thank you

**Comment by davechesebrough** [comment]
For reference to other Elasticsearch users, you might be looking for `http.cors.enabled` - as of 2.0: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html

**Comment by foxinni** [comment]
Paste this into `config/elasticsearch.yml`

```
http.cors.enabled: true
http.cors.allow-origin: "*"
```

**Comment by Iltony** [comment]
In my case changing the http.cors does not work. But I have installed a chrome extension https://chrome.google.com/webstore/detail/elasticsearch-head/ffmkiejjmecolpfloofpjologoblkegm
and this allowed me to connect to the cluster.

![image](https://user-images.githubusercontent.com/14924015/64083507-5665a080-ccf7-11e9-9d1f-adb5a6524dad.png)
