### ISSUE TITLE
install mobz/elasticsearch-head plugin failing with SSLHandshakeException[Received fatal alert: handshake_failure]

### ISSUE THREAD

**Issue by nihilson** [mobz/elasticsearch-head#190]
Getting the below failure message when trying to install the head plugin.  Am I missing something ?

C:\Nihilson\ElasticSearch\elasticsearch-1.4.0\bin>plugin -install mobz/elasticsearch-head --verbose
-> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip...
Failed: SSLHandshakeException[Received fatal alert: handshake_failure]
Failed to install mobz/elasticsearch-head, reason: failed to download out of all possible locations..., use --verbose to get detailed

**Comment by mobz** [comment]
there has been major ssl bug release recently. it's probably related to that. the download is from github. you can install plugins manually which might be the way to go

**Comment by nihilson** [comment]
The download provides me with this "elasticsearch-head-master.zip" and I am not sure how to manually install plugins from this ? Any pointers ?

**Comment by mobz** [comment]
https://www.google.com/webhp?q=elasticsearch%20manually%20install%20plugins first link

**Comment by nihilson** [comment]
sorry, may be my previous question was not put correctly.. I understand manually installing a plugin is matter of extracting the plugin under the plugins folder. But it was not clear with the directory structure that needs to be followed under the plugins directory..  a mere extract did not work though.. So I pulled the plugin and installed from local path like below and it worked :-)

C:\Nihilson\elasticsearch-1.4.0\bin>plugin --url file:///C:\Nihilson\elasticsearch-he
nstall mobz/elasticsearch-head
-> Installing mobz/elasticsearch-head...
Trying file:/C:/Nihilson/elasticsearch-head-master.zip...
Downloading .........DONE
Installed mobz/elasticsearch-head into C:\Nihilson\elasticsearch-1.4.0\plugins\head
Identified as a _site plugin, moving to _site structure ...
..... 
....
[2015-03-20 11:03:00,057][INFO ][node                     ] [Doorman] version[1.4.0], pid[8092], build[bc94bd8/2014-11-05T14:26:12Z]
[2015-03-20 11:03:00,058][INFO ][node                     ] [Doorman] initializing ...
[2015-03-20 11:03:00,070][INFO ][plugins                  ] [Doorman] loaded [], sites [head]
