### ISSUE TITLE
head plugin vs shield

### ISSUE THREAD

**Issue by cello86** [mobz/elasticsearch-head#191]
Hi all,
I'm testing the shield plugin on my Elasticsearch cluster but after the installation the head plugin can't connect to the nodes, because it requires authentication.

Is it possible to configure the authentication on head?

Marello

**Comment by bbonnin** [comment]
Hello,

I also use head with shield and in order to connect to the cluster, in the text box where you're setting the http address, I use the following syntax: http://username:password@localhost:9200 (). 

Bruno

**Comment by nielsen-brian-p** [comment]
I'm having a similar issue - it was working fine, and all of the sudden i'm continually prompted by shield for the admin username and password I've set up (and is working!)

**Comment by nielsen-brian-p** [comment]
FYI - I did try bbonnin's idea, with no luck

**Comment by karlito40** [comment]
Same problem here

**Comment by derfloscher** [comment]
+1 same problem

**Comment by mobz** [comment]
Have you guys tried setting authentication parameters as described here? https://github.com/mobz/elasticsearch-head#url-parameters

**Comment by karlito40** [comment]
Well, i tried again without any url parameters... and it is working now. :+1:

I don't know why though

**Comment by rohitCloud** [comment]
still not working for me :(

**Comment by karlito40** [comment]
There is another solution if you are on aws. 

Remove the shield plugin and create a security group for your elastic instances that allows your ip and your other instances.

**Comment by Kevin-Lee** [comment]
Isn't there any proper solution yet?

I did what https://github.com/mobz/elasticsearch-head#url-parameters says but not sure if it's a correct way.

Mine is
```
http://localhost:9200/_plugin/head/index.html?base_uri=http://localhost:9200&auth_user=some_username&auth_password=some_password
```
and it doesn't work.

I have shield installed. Without shield there's no issue, but with it, I get `cluster health: not connected`.

**Comment by philipskokoh** [comment]
Check your elasticsearch.yml. `*` for `http.cors.allow-origin` is not allowed for credentialed requests.

**Comment by tgensol** [comment]
Same for me, It was working before I install shields, but now I only have : cluster health: not connected. I am using ES 2.3

**Comment by fgdgtz183** [comment]
@Kevin-Lee  hi,I have shield installed and es-head not connected, you solution it yet?

**Comment by philipskokoh** [comment]
When you are using authentication, Ensure that you add `http.cors.allow-headers: Authorization`. (https://github.com/mobz/elasticsearch-head#basic-authentication)
Then specify auth_user and auth_password as url parameter
Check this guideline: https://github.com/mobz/elasticsearch-head#x-pack

**Comment by fgdgtz183** [comment]
@philipskokoh I did it，but still failed . my elasticsearch.yml config http.cors.enabled: true .http.cors.allow-origin: "*". http.cors.allow-headers: Authorization network.host:0.0.0.0  and url is http://xxx.xx.xx.x:9200/_plugin/head/index.html?base_url=http://xxx.xx.xx.x:9200/?auth_user=elastic&auth_password=changeme

**Comment by philipskokoh** [comment]
Hi @fgdgtz183,
I think there's no default `elastic` user in shield for elasticsearch 2.4.x. You need to add your first shield user through command line. Follow this guideline:
https://www.elastic.co/guide/en/shield/current/enable-basic-auth.html

Assume your new shield user is es_admin, and the password is es_admin_password,
if you can get response for `curl -XGET 'http://es_admin:es_admin_password@localhost:9200'`, then you should be able to access your cluster for elasticsearch-head. I just tested this case on elasticsearch-2.4.0.

I also notice that `_stats` on this elasticsearch version may return unexpected error message (HTTP response 404), if you have no indices in your cluster. So if you cluster is new and you haven't created a new index, create one new index using 
`curl -XPUT 'http://es_admin:es_admin_password@localhost:9200/test'`

**Comment by fgdgtz183** [comment]
hi @philipskokoh 
I created an admin user in shield,curl -XGET 'http://es_admin:es_admin_password@localhost:9200，it is working，but es-head not.

At first ,i was using es-head as a plugin of Elasticsearch and open http://localhost:9200/_plugin/head/，It needs to enter a user name and password,but the head plugin can't connect to the nodes，then i remove the head plugin，i tried it running with built in server and specify auth_user and auth_password as url parameters ：
http://localhost:9100/?auth_user=es_admin&auth_password=es_admin_password /，still not working for me .

**Comment by philipskokoh** [comment]
This is my setting to replicate your issue:
1. config/elasticsearch.yml
```
http.cors.enabled: true
http.cors.allow-origin: '*'
http.cors.allow-headers: Authorization
```

2. Shield installed, and then I add a user called `es_admin` with password `es_admin`.  

3. Elasticsearch is running as standalone server. I connect to the cluster using via this url:
`localhost:9100/?base_uri=http://localhost:9200&auth_user=es_admin&auth_password=es_admin`

**Comment by fgdgtz183** [comment]
@philipskokoh 
it is working now,beacause my cluster is new and no any indices. thanks for your notice. :)
