### ISSUE TITLE
if number value is over 2^53, that number is changed to wrong number because of Double-precision floating-point format

### ISSUE THREAD

**Issue by KangYongKyun** [mobz/elasticsearch-head#194]
At Any Request tab, I have search with query like below

```javascript
{
  "size": 100,
  "query": {
    "match_all": {}
  },
  "filter": {
    "bool": {
      "must": [
        {
          "term": {
            "LOG_NO": 742241735434043392
          }
        }
      ]
    }
  }
}
```

after Request, query is chaged to 

```javascript
{
  "size": 100,
  "query": {
    "match_all": {}
  },
  "filter": {
    "bool": {
      "must": [
        {
          "term": {
            "LOG_NO": 742241735434043400
          }
        }
      ]
    }
  }
}
```

LOG_NO is changed from 742241735434043392 to 742241735434043400

For Processing large number, you maybe need to use external library
example : https://github.com/silentmatt/javascript-biginteger

**Comment by KangYongKyun** [comment]
In jquery.js's parseJSON: function( data ) , window.JSON.parse( data ) call is not cover large number

**Comment by mobz** [comment]
see #165
