### ISSUE TITLE
cluster health: not connect

### ISSUE THREAD

**Issue by craigcosmo** [mobz/elasticsearch-head#199]
when run as a web app, I receive error cluster health: not connect

![screen shot 2015-07-26 at 10 14 32 pm](https://cloud.githubusercontent.com/assets/538657/8894540/291fa388-33e4-11e5-8902-715c4f9ae8eb.png)

**Comment by lucassaldanha** [comment]
Can you provide more details about your environment? I can't reproduce this error locally. Even running as a web everything works as expected.

**Comment by mobz** [comment]
This is probably a CORS error. have a look at the elasticsearch docs for information on how to fix this
