### ISSUE TITLE
Can't install plugin with elasticsearch 2.0.0-beta1

### ISSUE THREAD

**Issue by extesy** [mobz/elasticsearch-head#201]
I'm trying new elasticsearch version (see https://www.elastic.co/blog/elasticsearch-2-0-0-beta1-released) but this plugin isn't compatible, some required file is missing.

/cc @mobz

**Comment by remyderuysscher** [comment]
I can agree. 

Verifying https://github.com/mobz/elasticsearch-head/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by hmalphettes** [comment]
I started work on ES-2.0 support here: https://github.com/mobz/elasticsearch-head/pull/202
At this point, the plugin installs correctly and one can display the cluster and indices status page.

**Comment by nishaaaaa** [comment]
same error on my end :-(

**Comment by ddes** [comment]
same for me, hope it will be compatible soon, what a great plugin !

**Comment by tungpd** [comment]
same error for me,

**Comment by 41410** [comment]
Work on AWS EC2 Ubuntu Server
>java version "1.8.0_60"
>Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
>Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

But get error(Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify) on Synology server

>java version "1.8.0_51"
>Java(TM) SE Embedded Runtime Environment (build 1.8.0_51-b07, headless)
>Java HotSpot(TM) Embedded Client VM (build 25.51-b07, mixed mode)

**Comment by jmichaelprobert** [comment]
Same issue for me.

**Comment by brettnkc** [comment]
same issue for me as well

**Comment by Leathel** [comment]
Is there no fix for this?

**Comment by reginaldojunior** [comment]
Same issue for me!

**Comment by hoangton** [comment]
try this and have same issue

http://developer.couchbase.com/documentation/server/4.0/connectors/elasticsearch-2.1/install-intro.html
https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/installation.html

./plugin install  http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip


bin]# ./plugin install  http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip
-> Installing from http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip...
Trying http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip ...
Downloading ...................................................DONE
Verifying http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip checksums if available ...
Failed: IOException[Server returned HTTP response code: 403 for URL: http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip.sha1]; nested: IOException[Server returned HTTP response code: 403 for URL: http://packages.couchbase.com.s3.amazonaws.com/releases/elastic-search-adapter/2.1.1/elasticsearch-transport-couchbase-2.1.1.zip.sha1]; 
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by milodky** [comment]
I'm using es 2.0.0 and successfully installed head:
sudo bin/plugin install mobz/elasticsearch-head
-> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip ...
Downloading ................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/mobz/elasticsearch-head/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed head into /usr/share/elasticsearch/plugins/head

However when I was trying to install bigdesk, it threw an error:
sudo bin/plugin -install lukas-vlcek/bigdesk
ERROR: unknown command [-install]. Use [-h] option to list available commands
[ec2-user@ip-10-2-179-239 elasticsearch]$ sudo bin/plugin install lukas-vlcek/bigdesk
-> Installing lukas-vlcek/bigdesk...
Trying https://github.com/lukas-vlcek/bigdesk/archive/master.zip ...
Downloading .......................................................................................................................................................................................................................DONE
Verifying https://github.com/lukas-vlcek/bigdesk/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by eromoe** [comment]
D:\elasticsearch-2.0.0\bin>plugin install medcl/elasticsearch-analysis-ik
-> Installing medcl/elasticsearch-analysis-ik...
Trying https://github.com/medcl/elasticsearch-analysis-ik/archive/master.zip ...
Downloading ............................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
........................................................................................................................
......................................................................DONE
Verifying https://github.com/medcl/elasticsearch-analysis-ik/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by phutchins** [comment]
Same when trying to install bigdesk... Any way to disable the check?

**Comment by Leathel** [comment]
I had this issue and I was able to fix it by manually placing a plugin-descriptor.properties file in the plugin root folder.
Here is a link to my plugin-descriptor.properties in both .txt and.properties https://drive.google.com/folderview?id=0BxIqatqi4DWcSFRuYTE1ZWhSQUE&usp=sharing

This file is setup for Marvel so you may have to change the UNCOMMENTED attributes to suit your needs.

**Comment by phutchins** [comment]
I did the same for another plugin but wasn't quite able to get it working all of the way. Got stuck with the full path to the class...

**Comment by RadekHavelka** [comment]
same issue, ICU plugin ...

**Comment by elbow-jason** [comment]
same issue. :(

**Comment by isequal2** [comment]
same issue...not able to install bigdesk plugin

**Comment by LxiaoGirl** [comment]
same issue...elasticsearch jdbc

**Comment by charlescui** [comment]
same issue

/usr/share/elasticsearch$ sudo ./bin/plugin install mobz/elasticsearch-head --verbose
-> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip ...
Downloading ......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/mobz/elasticsearch-head/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)

**Comment by dongy** [comment]
same issue

**Comment by vg15** [comment]
So I have another Issue to report for head plugin , Chrome web browser was
not allowing to download more than 250 documents in CSV format . So I tried
it with Firefox , it is fine till 1000 documents but firefox crashes if I
select 5000 documents .Any idea which browser is compatible with head
plugin ?

Thanks
VG

On Fri, Dec 11, 2015 at 1:32 AM, Dong Yan <notifications@github.com> wrote:

> same issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mobz/elasticsearch-head/issues/201#issuecomment-163734661>
> .
>



-- 
*Regards,*
*Vikas Gopal*

**Comment by klein0r** [comment]
same issue...

**Comment by knoldernarayan** [comment]
I have also same problem
```ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip```

**Comment by philipskokoh** [comment]
I am not sure what causes the problem, but can you try from the latest branch?
`plugin install philipskokoh/elasticsearch-head/ES2-support`

**Comment by aaae** [comment]
same issue...not able to install Search Guard Security Plugin.

**Comment by knoldernarayan** [comment]
Thanks @philipskokoh for quick response

**Comment by berenicepiste** [comment]
Some can fix it? i have same error

**Comment by philipskokoh** [comment]
@berenicepiste: can you be more specific about the error?
You can use this command to install elasticsearch-head
`sudo elasticsearch/bin/plugin install mobz/elasticsearch-head`

**Comment by ayushsangani** [comment]
I was able to install plugin successfully on ES 2.1.2
Thanks guys for keeping Head plugin updated with ES release.

**Comment by JoseTomasTocino** [comment]
I'm getting a different error:

```
# /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head --verbose
-> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip ...
Failed: SocketException[java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)]; nested: NoSuchAlgorithmException[Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)]; nested: ProviderException[nextBytes() failed]; nested: IOException[Bad file descriptor]; 
ERROR: failed to download out of all possible locations..., use --verbose to get detailed information

```

Any clue?

**Comment by prashantzed** [comment]
how did you resolve the issue?
I am using ES2.2.0 and trying to install "elasticsearch-csv-master.zip".
 ./plugin install  file:/es/downloads/elasticsearch-csv-master.zip csv-master

**Comment by chilakilez** [comment]
Same here.

**Comment by abla00** [comment]
I use the command to install [analysis-kuromoji](https://github.com/elastic/elasticsearch-analysis-kuromoji)
`sudo bin/plugin install elasticsearch/elasticsearch-analysis-kuromoji/2.7.0`
Same error
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

Then use the command in [docs](https://www.elastic.co/guide/en/elasticsearch/plugins/master/analysis-kuromoji.html)
`sudo bin/plugin install analysis-kuromoji`
It works!!

**Comment by yujintang** [comment]
same issue

**Comment by yetsun** [comment]
same here 

#./bin/plugin install lukas-vlcek/bigdesk/2.4.0
-> Installing lukas-vlcek/bigdesk/2.4.0...
Trying https://download.elastic.co/lukas-vlcek/bigdesk/bigdesk-2.4.0.zip ...
Trying https://search.maven.org/remotecontent?filepath=lukas-vlcek/bigdesk/2.4.0/bigdesk-2.4.0.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/lukas-vlcek/bigdesk/2.4.0/bigdesk-2.4.0.zip ...
Trying https://github.com/lukas-vlcek/bigdesk/archive/2.4.0.zip ...
Trying https://github.com/lukas-vlcek/bigdesk/archive/master.zip ...
Downloading .........................................................................................................................................................................................................................................................DONE
Verifying https://github.com/lukas-vlcek/bigdesk/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by johncornelius091** [comment]
fix it , bash script:
cd elasticsearch-2.0.0/plugins; 
git clone https://github.com/lukas-vlcek/bigdesk;
mkdir _site;
mv bigdesk/* _site;
mv _site bigdesk;
echo "description=bigdesk" >> bigdesk/plugin-descriptor.properties;
echo "version=master" >> bigdesk/plugin-descriptor.properties;
echo "site=true" >> bigdesk/plugin-descriptor.properties;
echo "name=bigdesk" >> bigdesk/plugin-descriptor.properties;
sed -i"" 's/major == 1/major >= 1/' bigdesk/_site/js/store/BigdeskStore.js;

**Comment by johncornelius091** [comment]
For elasticsearch head plugin, 

though it says unable to verify the checksum, it installs perfect.
Just open it in browser, 
http://127.0.0.1:9200/_plugin/head/

**Comment by hkhalidz** [comment]
This works if you replace `--instal`l with `install`.

**Comment by Tenzil** [comment]
Has anybody solved it. I still couldn't install ICU plugin .

 curl -XGET 'localhost:9200' 
{
  "name" : "D'Spayre",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}


sudo bin/plugin install elasticsearch/elasticsearch-analysis-icu/2.7.0
-> Installing elasticsearch/elasticsearch-analysis-icu/2.7.0...
Trying https://download.elastic.co/elasticsearch/elasticsearch-analysis-icu/elasticsearch-analysis-icu-2.7.0.zip ...
Downloading ............................DONE
Verifying https://download.elastic.co/elasticsearch/elasticsearch-analysis-icu/elasticsearch-analysis-icu-2.7.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip
webonise@webonise-Desktop:/usr/share/elasticsearch$ sudo bin/plugin --install elasticsearch/elasticsearch-analysis-icu/2.7.0
ERROR: unknown command [--install]. Use [-h] option to list available commands

**Comment by yeasy** [comment]
Same error to install plugins like head/bigdesk with elasticsearch 2.3.

**Comment by prikha** [comment]
@Tenzil look at elasticsearch master https://github.com/elastic/elasticsearch/tree/master/plugins
your plugins are already there.

**Comment by philipskokoh** [comment]
@tenzil: if you are using elasticsearch-2.x, install using `bin/plugin install mobz/elasticsearch-head`. Only use -install for older elasticsearch version (v 1.x and 0.9).

@yeasy: I tried installing elasticsearch-head in Elasticsearch-2.3.3. It worked. You should see something like this when you install elasticsearch-head
```
$ bin/plugin install mobz/elasticsearch-head
-> Installing mobz/elasticsearch-head...
Trying https://github.com/mobz/elasticsearch-head/archive/master.zip ...
Downloading .......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/mobz/elasticsearch-head/archive/master.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
Installed head into /home/user1/elasticsearch-2.3.3/plugins/head
```

**Comment by zsgking** [comment]
i met the same issue

**Comment by chromechris1** [comment]
Same

**Comment by rovkxu** [comment]
i met the same issue and i used other repository。 
https://github.com/hlstudio/bigdesk

**Comment by justein** [comment]
@rovkxu THX ,it works! ES2.2.1
