### ISSUE TITLE
Structured Query: Can not choose (true or false) to a boolean field

### ISSUE THREAD

**Issue by bogdanvlviv** [mobz/elasticsearch-head#210]
onoff - boolean type

I choose
must      type.onoff       #Can not add choose (true or false) to a boolean field
{
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {}
        }
      ],
      "must_not": [],
      "should": []
    }
  },
  "from": 0,
  "size": 10,
  "sort": [],
  "facets": {}
}

need =>

{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "onoff": # true or false
          }
        }
      ],
      "must_not": [],
      "should": []
    }
  },
  "from": 0,
  "size": 10,
  "sort": [],
  "facets": {}
}

**Comment by philipskokoh** [comment]
I add 'term' ops for boolean type since that is the default operation for boolean type.
https://www.elastic.co/guide/en/elasticsearch/reference/2.0/boolean.html

The update reflected on #218
