### ISSUE TITLE
Doc count reporting double for 1.7.3

### ISSUE THREAD

**Issue by nariman-haghighi** [mobz/elasticsearch-head#213]
Something changed in the last few commits such that the primary cluster overview screen now reports ```docs``` and ```size``` as exactly double (e.g. docs: 600,076 (662,115)) but if you select info -> index status and look under ```primaries``` the correct values are reported:

```
"primaries": {
"docs": {
"count": 300038,
"deleted": 31679
}
```

**Comment by my-dev** [comment]
hi!
mr. nariman-haghighi.

I'm sorry of a sudden.
please tell me, The reason you closed this issue...
I'm under same situation.
