### ISSUE TITLE
[docs's count] is different from [Browser tab's hits count]...Just twice as high.

### ISSUE THREAD

**Issue by my-dev** [mobz/elasticsearch-head#215]
Hi!

Thank you for your development this plugin.

Now, i use [ Overview tab ] mainly...and check [ docs count ].
Then change tab to [ Browser tab ], and check [ xxx hits ].
[ docs count ] is about twice as higher than [ xxx hits ]...

Elasticsearch's Version is 1.7.3

\------------------------------
( ex )
docs: 26 (26) In Overview Tab...
Searched 5 of 5 shards. 13 hits. 0.007 seconds In Browser Tab...
\------------------------------

And...

##### curl -XGET http://localhost:9200/_cat/count/index_name?pretty=true
Elasticsearch's response is [ 13 ]. It's correct...

##### Maybe, [ index.status.total.docs.count ] of [ _site/app.js ( Line about 3213 ) ]...
[ index.status.total.docs.count ] is doubled value...

If you can do, please check it.

thank you...

**Comment by my-dev** [comment]
Hi!

I got the resolution...

##### [ index.status.total.docs.count ] -> [ index.status.primaries.docs.count ]

**Comment by philipskokoh** [comment]
Yes.
.primary is the number from primary shards only.
.total is the number from primary and replica shards.

I made some changes on overview tab (#218). I hope that solved this issue.

**Comment by my-dev** [comment]
Hi!
I see.

But i think a different approach, Because It's displayed [ twice as high ]... You know.
uh-----.nh-------

But i understood.

thank you.
