### ISSUE TITLE
ES 2 support - unable to see data on browser tab

### ISSUE THREAD

**Issue by avibh** [mobz/elasticsearch-head#217]
when on the browser tab I get the following exception -

[INFO ][rest.suppressed          ] /_all/_search Params: {index=_all}
Failed to execute phase [query], all shards failed; shardFailures {[IqVK4SR4S_inF3OU-kp-LQ][case][0]: RemoteTransportException[[Mangle][localhost/127.
0.0.1:9320][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"fields":["_parent","_source"],"quer
y":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from":0,"size":50,"sort":[],"facets":{},"version":true}]]; nested: SearchParseExcep
tion[failed to parse search source. unknown search element [facets]]; }{[IqVK4SR4S_inF3OU-kp-LQ][case_4_cases][0]: RemoteTransportException[[Mangle][l
ocalhost/127.0.0.1:9320][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"fields":["_parent","_s
ource"],"query":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from":0,"size":50,"sort":[],"facets":{},"version":true}]]; nested: Sea
rchParseException[failed to parse search source. unknown search element [facets]]; }{[IqVK4SR4S_inF3OU-kp-LQ][config-data][0]: RemoteTransportExceptio
n[[Mangle][localhost/127.0.0.1:9320][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"fields":["
_parent","_source"],"query":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from":0,"size":50,"sort":[],"facets":{},"version":true}]];
 nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[IqVK4SR4S_inF3OU-kp-LQ][crime][0]: RemoteTransportEx
ception[[Mangle][localhost/127.0.0.1:9320][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"fiel
ds":["_parent","_source"],"query":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from":0,"size":50,"sort":[],"facets":{},"version":tr
ue}]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[IqVK4SR4S_inF3OU-kp-LQ][customized-filter][0]:
 RemoteTransportException[[Mangle][localhost/127.0.0.1:9320][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse sea
rch source [{"fields":["_parent","_source"],"query":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from":0,"size":50,"sort":[],"facet
s":{},"version":true}]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[IqVK4SR4S_inF3OU-kp-LQ][extr
actions][0]: RemoteTransportException[[Mangle][localhost/127.0.0.1:9320][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed
to parse search source [{"fields":["_parent","_source"],"query":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from":0,"size":50,"sor
t":[],"facets":{},"version":true}]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[IqVK4SR4S_inF3OU
-kp-LQ][persons][0]: RemoteTransportException[[Mangle][localhost/127.0.0.1:9320][indices:data/read/search[phase/query]]]; nested: SearchParseException
[failed to parse search source [{"fields":["_parent","_source"],"query":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from":0,"size"
:50,"sort":[],"facets":{},"version":true}]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }{[IqVK4SR4
S_inF3OU-kp-LQ][projects][0]: RemoteTransportException[[Mangle][localhost/127.0.0.1:9320][indices:data/read/search[phase/query]]]; nested: SearchParse
Exception[failed to parse search source [{"fields":["_parent","_source"],"query":{"bool":{"must":[],"must_not":[],"should":[{"match_all":{}}]}},"from"
:0,"size":50,"sort":[],"facets":{},"version":true}]]; nested: SearchParseException[failed to parse search source. unknown search element [facets]]; }
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction.onFirstPhaseResult(TransportSearchTypeAction.java:228)
        at org.elasticsearch.action.search.type.TransportSearchTypeAction$BaseAsyncAction$1.onFailure(TransportSearchTypeAction.java:174)
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:821)
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:799)
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:361)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: SearchParseException[failed to parse search source. unknown search element [facets]]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:841)
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:663)
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:632)
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:374)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:
368)
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:
365)
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        ... 3 more

**Comment by maxflow7934** [comment]
+1

**Comment by JLVeiga** [comment]
+1

**Comment by ricardofalasca** [comment]
+1

**Comment by yiyuqiuchi** [comment]
+1

**Comment by eamosov** [comment]
+1

**Comment by sibagatov** [comment]
This is because "facet" element has been depricated : 
```javascript
{"error":{"root_cause":[{"type":"search_parse_exception","reason":"failed to parse search source. unknown search element [facets]","line":1,"col":132}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"1","node":"qKrSbtgXT0qEhpbqcrEx-g","reason":{"type":"search_parse_exception","reason":"failed to parse search source. unknown search element [facets]","line":1,"col":132}}]},"status":400}
```

**Comment by unlimitedLoop** [comment]
Is there a plan to update?

**Comment by net239** [comment]
+1

**Comment by inteloid** [comment]
well, +1

**Comment by philipskokoh** [comment]
I made some changes on breaking errors. #218 should fix this.

**Comment by dlamichhane** [comment]
Thanks  [philipskokoh](https://github.com/philipskokoh). It works for me!

**Comment by digitalrinaldo** [comment]
How do I get #218.

**Comment by dlamichhane** [comment]
I forked the [mobz/elasticsearch-head](https://github.com/mobz/elasticsearch-head) and I merged the pull request #218  from  [philipskokoh](https://github.com/philipskokoh)

**Comment by digitalrinaldo** [comment]
thanks -- I assume I should just download the plugin and not use plugin install.

**Comment by Ardoise** [comment]
+1
aused by: SearchParseException[failed to parse search source. unknown search element [facets]]

**Comment by memect** [comment]
+1

**Comment by digitalrinaldo** [comment]
The above branch doesn't address the data browsing issue in 2.0. If you click on an index and a type the data is not displayed.

**Comment by philipskokoh** [comment]
@digitalrinaldo: Elasticsearch mapping is changed in 2.0. A field name cannot be referenced by short name anymore. Reference:
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_fields_cannot_be_referenced_by_short_name

Browser tab lists all fields in the cluster using short name. I feel the UI is not so suitable anymore with the new ES 2.0 changes. When we select a field, it's not clear which field are we refering to.
I would suggest to use structured query tab to browse the data. How we compose query is clearer there.

I would leave UI design decision for browser tab to @mobz

**Comment by oliverhuang** [comment]
+1

**Comment by giuseppedicarlo** [comment]
+1

**Comment by croblee** [comment]
+1

**Comment by kinghs** [comment]
+1

**Comment by philipskokoh** [comment]
@digitalrinaldo: I fixed short name issue in browser tab. Full path is used in the filter fields. You can check the latest update.

**Comment by avibh** [comment]
thanks to @philipskokoh & @dlamichhane I finally got it working!
hope @philipskokoh's PR is accepted ASAP

**Comment by RicherdLee** [comment]
thanks to @philipskokoh & @dlamichhane,It can work.

**Comment by philipskokoh** [comment]
I just updated my branch to address facet issue. Facet is removed, and it's using aggregation now.
You can check the latest #218.

**Comment by vg15** [comment]
@ philipskokoh   , I am facing one more issue .I am not able to export more than 250 records to a CSV. Nothing is happening when I am clicking on download link if the number of results is greater than 250.

**Comment by 117111302** [comment]
+1

**Comment by syunusic** [comment]
+1

**Comment by Liuchy1** [comment]
+1

**Comment by klein0r** [comment]
+1

**Comment by renaud** [comment]
+1

**Comment by skylarmb** [comment]
+1

**Comment by wsldl123292** [comment]
+1

**Comment by mikeyhogarth** [comment]
+1
