### ISSUE TITLE
Incorrect doc number in the head plugin

### ISSUE THREAD

**Issue by quixeyhd** [mobz/elasticsearch-head#225]
I created an index called my index with 3 shards and put some data in it.

On the front page of the head plugin, it shows:
my_index
size: 122Gi (122Gi)
docs: 159,579,321 (181,136,693)

However, the info -> index status dialog shows that:
"docs": {
  "count": 53193107,
  "deleted": 7237315
}.
It's the same as the _status API.

I found that 159,579,321 = 53193107 * 3. But I don't know why the head plugin displayed the incorrect number.

**Comment by philipskokoh** [comment]
In index status there is:

```json
"primaries": {
  "docs": {
    "count": 1000,
    "deleted": 20
  }
},
"total": {
  "docs": {
    "count": 3000,
    "deleted": 60
  }
}

Primary indicates the number from primary shards, whereas total indicates the number from all shards (primaries + replicas).

Let's come back to the head plugin,
The number outside the bracket shows the number of documents you have. It's equal to `primaries.docs.count`. Deleted documents and replicas are not included here.
The number inside the bracket shows the total number of documents in the index. It's equal to `total.docs.count + total.docs.deleted`.

Hope this clarify the confusion.

**Comment by quixeyhd** [comment]
Sorry, I have 8 shards and 3 replicas. But what I meant was the difference between "docs: 159,579,321" and "docs.count: 53193107"

I just noticed that someone upgraded my ES cluster from 1.4.4 to 1.73. Before this upgrade, I remember the head plugin would show  "docs: 53193107" and "docs.count: 53193107". After the upgrade, it showed "docs: 159579321" and "docs.count: 53193107". So the head plugin behaves differently depending on ES version?

**Comment by philipskokoh** [comment]
I made some changes in my branch #218. You can see the changes and what fields inside from index status are taken here:
https://github.com/philipskokoh/elasticsearch-head/commit/97965dfc357be2d3b74ccbc9e9b42d0cafca793b
It's implementing what I explain in the previous comments. So if you install this version, the behavior is different from the previous version.

**Comment by quixeyhd** [comment]
Well, I see. Thanks!
