### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by Darkvador-a** [mobz/elasticsearch-head#242]
Hello ! 

I am new user to elasticsearch, when i open http://localhost:9200/_plugin/head/ after the  instalation of the  plugin elasticsearch head an empty page i have.

version use is  elasticsearch 1.7.3, same thing with 2.0, on win10
i also enable the  http.cors.enabled on true.  no change

Any idea ?

**Comment by jkubacki** [comment]
@Darkvador-a Plugin have js issues in some browsers. It opens fine for me in Safari, but not in Chrome.

**Comment by andyskipper** [comment]
@Darkvador-a I resolved this by selectively disabling Chrome extensions - the issue is with the i18n module in use, which dies if an extension injects a script tag during page load. In my case, it was a popup blocker, ProperBlocker, but I have a feeling many extensions will do the same.

**Comment by mobz** [comment]
@andyskipper  Can you post the error you get from the browser console, this may be fixable

**Comment by andyskipper** [comment]
@mobz Sure thing, check out issue #92, I attached a screen shot there. The issue is definitely with i18n.js and how it checks for script tags - I stepped through the code, and the language files are never loaded, hence the exception when applying CSS to any translated element

**Comment by mobz** [comment]
duplicate #92
