### ISSUE TITLE
Update installation instructions on mobz.github.io/elasticsearch-head

### ISSUE THREAD

**Issue by igouss** [mobz/elasticsearch-head#244]
**Currently:**
Running as a plugin of ElasticSearch (this is the preferred method)

elasticsearch/bin/plugin -install mobz/elasticsearch-head
open http://localhost:9200/_plugin/head/

**Should be:**
Running as a plugin of Elasticsearch

Install elasticsearch-head:
– for Elasticsearch 2.x:
sudo elasticsearch/bin/plugin install mobz/elasticsearch-head
– for Elasticsearch 1.x:
sudo elasticsearch/bin/plugin -install mobz/elasticsearch-head/1.x
– for Elasticsearch 0.9:
sudo elasticsearch/bin/plugin -install mobz/elasticsearch-head/0.9
open http://localhost:9200/_plugin/head/

**Comment by ericrepec** [comment]
Install elasticsearch-head:
**Currently:**

– for Elasticsearch 2.x:
sudo elasticsearch/bin/plugin install mobz/elasticsearch-head


**Should be:**
Install elasticsearch-head:
– for Elasticsearch 2.x:
sudo elasticsearch/bin/plugin install mobz/elasticsearch-head/2.x

**Comment by philipskokoh** [comment]
We don't have 2.x branch. We use master branch for 2.x (latest) Elasticsearch version.

**Comment by mobz** [comment]
Thanks for this issue
