### ISSUE TITLE
Display certain indices

### ISSUE THREAD

**Issue by Brasoveanul** [mobz/elasticsearch-head#247]
Hello,

Considering the "Structured Query" interface, how could I tell the Head Plugin to display in that drop down list only certain indices from Elasticsearch, and not all of them? Where could I find the relevant code that I could change, or else to accomplish this? Thank you in advance for any clarification on this!

**Comment by mobz** [comment]
I don't think this is a feature we would add to 'head. If you want to have a go you're self, you'll need to follow the advise around setting up the dev environment then have a look at `filterBrowser.js`

```			new data.MetaDataFactory({ cluster: this._cluster, onReady: function(metadata, eventData) {
				this.metadata = metadata;
                                // add this
                               this.metadata.indices = this.metadata.indices.filter( function( index) {
                                  return index.name === "foo"; // or something like this
                               });
				this._createFilters_handler(eventData.originalData.metadata.indices);
			}.bind(this) });
```

**Comment by Brasoveanul** [comment]
Hi,

Thank you for the advice. I have added the code that you mentioned at the respective place, both in filterBrowser.js and app.js, and also separately(one at a time) in these files. Unfortunately, the drop down list still displays all the indices, no filtering takes place.

**Comment by mobz** [comment]
Could be, you'll need to modify the values returned in the metadata param. It's been a while since i've been in this code, you'll just have to dig around to figure out how to get when you want.
