### ISSUE TITLE
elasticsearch-head will not work

### ISSUE THREAD

**Issue by JohnTian** [mobz/elasticsearch-head#252]
i use elasticsearch-2.3.1 currently. but the amazing plugin tool **elasticsearch-head** will not work. the message is 
ERR_CONNECTION_TIMED_OUT
anyone could help me out ?
thanks very much.

**Comment by mobz** [comment]
This is most likely something to do with your local network or the way elasticsearch is set up. It is not an issue with elasticsearch-head, which is just a webapp.
