### ISSUE TITLE
Can't install plugin with elasticsearch 5.0.0-alpha1

### ISSUE THREAD

**Issue by fadaytak** [mobz/elasticsearch-head#253]
hi,

I'm trying new elasticsearch version 5.0.0.alpha1 but this plugin isn't compatible.

**Comment by philipskokoh** [comment]
Looks like that elasticsearch-5.0.0-alpha1 has some changes in plugin module. Installing plugin via `./bin/elasticsearch-plugin` is currently not working. I am checking this issue with elasticsearch.

But you can run elasticsearch-head as standalone server. I have tested it. It's working. You can follow this guideline:
https://github.com/mobz/elasticsearch-head#running-with-built-in-server

**Comment by fadaytak** [comment]
not working for me !!

i have the plugin page but cannot connect to elasticsearch 

i have enabled cors by adding http.cors.enabled: true in elasticsearch configuration

but also not working and when i have enabled this option my kibana also was block with Authorization Exception

**Comment by philipskokoh** [comment]
You need both settings `http.cors.enabled` and `http.cors.allow-origin`. Try this:
```
http.cors.enabled: true
http.cors.allow-origin: "*"
```

Reference: 
https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-http.html

**Comment by asanderson** [comment]
According to the Elasticsearch 5.0.0-alpha3 breaking changes page, "**Site plugins should be reimplemented as Kibana plugins.**"  Are there any plans to refactor head as a Kibana plugin?

Reference: 
https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_plugins.html

**Comment by philipskokoh** [comment]
@asanderson: we have no plan to build Kibana plugin for Elasticsearch-head at the moment. 
You can run Elasticsearch-head as a standalone server and connect it to Elasticsearch 5.x.x.
https://github.com/mobz/elasticsearch-head#running-with-built-in-server

**Comment by zhouyongwei1** [comment]
ERROR: Unknown plugin mobz/elasticsearch-head

**Comment by prakash7755** [comment]
Me to getting same error as @zhouyongwei1 ... when i tried to install elasticsearch-head in fedora 27
