### ISSUE TITLE
No connection to ES cluster nodes

### ISSUE THREAD

**Issue by dirkhschulz** [mobz/elasticsearch-head#255]
I have installed elasticsearch-head (complete files) into an Apache webserver. Can call the index.html fine (without base_uri), but when I fill in an ES node to connect to and click "Connect" or use the ?base_uri= parameter ist says "cluster health: not connected". 

I tried /elasticsearch-head/index.html?base_uri=http://my.esno.de:9200/_cluster/health as well as 
/elasticsearch-head/index.html?base_uri=http://my.esno.de:9200 but both do not work. 

And - just in case :-) - I have tried the connection from the web server's command line - it works. 

So: Is there a bug or an undocumented step?

Cheers, 

Dirk

**Comment by mobz** [comment]
Could be a cross domain issue, where the browser is preventing access to the es head running on a different port/domain.

**Comment by dirkhschulz** [comment]
Hi, 

> Am 21.04.2016 um 08:14 schrieb Ben Birch <notifications@github.com>:
> 
> Could be a cross domain issue, where the browser is preventing access to the es head running on a different port/domain.
> 
Thanks for your answer - this seems not to be the case as the webserver and the ES server share the same domain and subdomain. 

Dirk
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/mobz/elasticsearch-head/issues/255#issuecomment-212761224>

Dirk H. Schulz
Inhaber / Owner
SchulzConsult
Wiesenweg 12, 85567 Grafing, Germany
www.sccon.de, dirk.schulz@sccon.de

**Comment by mobz** [comment]
Which version of ES are you using

**Comment by dirkhschulz** [comment]
Hi Ben, 

it is 2.3.1. 

Dirk
> Am 21.04.2016 um 08:51 schrieb Ben Birch <notifications@github.com>:
> 
> Which version of ES are you using
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/mobz/elasticsearch-head/issues/255#issuecomment-212770967>

Dirk H. Schulz
Inhaber / Owner
SchulzConsult
Wiesenweg 12, 85567 Grafing, Germany
www.sccon.de, dirk.schulz@sccon.de

**Comment by dirkhschulz** [comment]
Hi Ben, 

have to admin it was a CORS issue - I had enabled it, but not configured it. 

Now it works. 

Thanks for looking into this. 

Dirk
> Am 21.04.2016 um 08:51 schrieb Ben Birch <notifications@github.com>:
> 
> Which version of ES are you using
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <https://github.com/mobz/elasticsearch-head/issues/255#issuecomment-212770967>

Dirk H. Schulz
Inhaber / Owner
SchulzConsult
Wiesenweg 12, 85567 Grafing, Germany
www.sccon.de, dirk.schulz@sccon.de
