### ISSUE TITLE
incorrect size number in the head plugin

### ISSUE THREAD

**Issue by lbbds** [mobz/elasticsearch-head#264]
I created an index called my index with 10 shards and put some data in it by using "curl -s -XPOST localhost:9200/_bulk --data-binary @$file".

On the front page of the head plugin, it shows:
My_index
size: 48.6Mi (48.6Mi)
docs: 226,661 (226,661)

However, after reloading the current page, the "size" becomes:
My_index
size: 45.6Mi (45.6Mi)
docs: 226,661 (226,661)

[The number of size is down and the number of docs doesn't change. ]

When I refresh the page again, the number of size is up:
My_index
size: 47.6Mi (47.6Mi)
docs: 226,961 (226,961)

I refresh several times, the size is always up and down. (The number of docs doesn't change or goes up.)

What's happen? is it correct about the number of size? By the way, the version of my elasticsearch is 1.7.3

**Comment by mobz** [comment]
es-head just reports the values returned by the cluster  API's. whatever is happening, it's nothing to do with es-head
