### ISSUE TITLE
cannot connect to es 5.0.0-rc1

### ISSUE THREAD

**Issue by SweetNSourPavement** [mobz/elasticsearch-head#276]
Head fails to connect to elasticsearch 5.0.0-rc1, it displays "cluster health: not connected".
Es 5.0.0-beta1 seems to work, at least it will connect to it.

According to the browser console, it tries to `GET http://localhost:9200/_nodes/stats?all=true`, but the result is `400 Bad Request`. Here's the complete response:
> {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_nodes/stats] contains unrecognized parameter: [all]"}],"type":"illegal_argument_exception","reason":"request [/_nodes/stats] contains unrecognized parameter: [all]"},"status":400}

If I remove the `?all=true` query the result looks normal.

**Comment by philipskokoh** [comment]
Thanks for informing. `?all=true` does not exist anymore.
