### ISSUE TITLE
Unable to run ES Head on a ES 5.x Cluster

### ISSUE THREAD

**Issue by jamesl1234** [mobz/elasticsearch-head#278]
Hi. I have a newly installed Elasticsearch running on 5.0.
I also have an old 2.3.4 Elasticsearch that has ES-Head plugin installed.

I try to point my ES-Head plugin from 2.3.4 to the 5.0 but ES-Head just shows cluster health not connected.

I also have KOPF setup the same way and I can interrogate my 5.0 Cluster so I think my CORS is running ok?

Anything else I can check?

**Comment by philipskokoh** [comment]
check `http.cors.enabled` and `http.cors.allow-origin` are set in `config/elasticsearch.yml` in order to enable cors.
Reference : https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html

**Comment by jamesl1234** [comment]
Hi. Yes I tried this in my /etc/elasticsearch/elasticsearch.yml and restarted ES.

http.cors.enabled : true
http.cors.allow-origin : "*"

I also tried adding in these thinking maybe might need them:

http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length

But same, can't get HEAD to connect.

**Comment by jamesl1234** [comment]
Ahh ok I will upgrade my current clusters 2.3 HEAD, do i have to uninstall and then reinstall?

Re my ES 5.0 -  I don't have enough resources to spin up another Ubuntu host just for Head (unless I can run it on the same ES 5.0 box?

**Comment by jamesl1234** [comment]
Don't bother replying worked it out..
Where HEAD is installed
1. sh plugin remove head
2. sh plugin install mobz/elasticsearch-head

Done 👍 
I now can check out my new cluster.
Happy Admin :)

**Comment by philipskokoh** [comment]
Good! Actually, you can run standalone ES-head on the same ES5.0 box. By default, the ES-head is running on port 9100.

**Comment by jamesl1234** [comment]
Hi. I tried to do exactly that (go through the procedure to install it on the same box as standalone but NPM has failed to install...
Steps I followed were:

1. git clone git://github.com/mobz/elasticsearch-head.git - good.
2. cd elasticsearch - good.
3. npm install - complained and said I needed to run apt install npm so I did - failed with lots of errors on the screen.

See error message posted below.
OS is Ubuntu 16.04.
root@elas50:~/elasticsearch-head# sudo npm install
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> phantomjs@1.9.20 install /root/elasticsearch-head/node_modules/phantomjs
> node install.js

sh: 1: node: not found
elasticsearch-head@0.0.0 /root/elasticsearch-head
├─┬ grunt@0.4.5
│ ├─┬ findup-sync@0.1.3
│ │ └── lodash@2.4.2 
│ └─┬ grunt-legacy-log@0.1.3
│   ├─┬ grunt-legacy-log-utils@0.1.1
│   │ └── lodash@2.4.2 
│   └── lodash@2.4.2 
├─┬ grunt-karma@0.8.3
│ └── lodash@2.4.2 
└─┬ karma@0.12.16
  └── lodash@2.4.2 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN elasticsearch-head@0.0.0 license should be a valid SPDX license expression
npm ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs@1.9.20 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.20 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/elasticsearch-head/npm-debug.log

**Comment by philipskokoh** [comment]
It seems that you do not have nodejs. You need to install nodejs first
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by jamesl1234** [comment]
Am I better off installing Node.js 4.x or 6.x?

**Comment by philipskokoh** [comment]
newer nodejs should be better for you

**Comment by jamesl1234** [comment]
Thanks. done that and seems to have installed nodejs okay.

tried to install npm but that bombed out as per below:
root@elas50:~# sudo apt-get install -y npm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by philipskokoh** [comment]
nodejs comes with npm. The one in apt-get is an older version.

**Comment by jamesl1234** [comment]
thanks.
how best to run 'grunt server' ?

**Comment by inscrutabledude** [comment]
@jamesl1234  your question is rather vague, but if you want it to run and not hang your terminal, just use grunt server &
You'll have to CTRL-C after, but it will continue to run in the background.

That said, I have a question.  **Is there a significant difference between elasticsearch 5.1.2 and 5.0.0.2 such that elastic-head won't connect properly?**

I had 5..1.2 running with head, and it worked.  It was on a vm on my laptop, but anyone on the LAN could connect to it.  Now that I have it running on Azure, with v5..0.0.2, no joy.  I've switched up the host IP between localhost, the lan ip and the public ip, but nothing seems to work.  All cors configs have been done, numerous reboots and service restarts as well.  

Any help appreciated, thanks!

**Comment by jamesl1234** [comment]
I have put in these values in my elasticsearch.yml:
http.cors.enabled : true
http.cors.allow-origin : "*"

And am running Head via Docker --> 
docker run -p 9100:9100 mobz/elasticsearch-head:5

Then http://localhost:9100


and it works all the time :) very happy !
