### ISSUE TITLE
cluster health: not connected

### ISSUE THREAD

**Issue by jaishals** [mobz/elasticsearch-head#282]
I did a fresh install of elastic search 5.0 and am running head as a standalone server. 
Head plugin displays cluster health as : not connected.

Is this a known problem in 5.0

I have  http options set in yml file
http.cors.enabled: true
http.cors.allow-origin: "*"

Please let me know

**Comment by philipskokoh** [comment]
It should work. Your http.cors configuration is correct.
Check your firewall

**Comment by jaishals** [comment]
The firewall is disabled on ubuntu for now

**Comment by philipskokoh** [comment]
Still not working? any error messages?
It works fine on my machine

**Comment by jaishals** [comment]
No it did not work. It might be something to do with ES v5.0. I was able to access ip:9200 remotely with v2.4.1. But now in v5.0 that also is not working. I will try couple of other things and update you here.

**Comment by jaishals** [comment]
I fixed few issues in elastic search setup and now  I am able to use HEAD standalone servers with 5.0. It was mainly config related issues nothing on es-head plugin. Thanks for your help

**Comment by fitsanju** [comment]
Hi Jaishals

what the issuse in conifg i m also facing the same issuse.

i had done following steps
git clone git://github.com/mobz/elasticsearch-head.git
cd elasticsearch-head
npm install
grunt server
open http://localhost:9100/

I have http options set in yml file
http.cors.enabled: true
http.cors.allow-origin: "*"


Head plugin displays cluster health as : not connected.

**Comment by fgdgtz183** [comment]
@fitsanju hi,i have the same issuse，you solution it yet?

**Comment by very9527** [comment]
I have the same issue.

**Comment by maggienj** [comment]
same issue. any resolutions?

**Comment by hbarnard** [comment]
I am using elasticsearch 1.7.3 on Amazon Web Services Ubuntu. When I put the external IP address into the top box, it connects from my home machine, but gives 'not connected' from any other (tried to demo and then tried a neighbour). I've got all TCP open at the moment, but obviously don't want to keep that. So, this is still a mystery.
