### ISSUE TITLE
How to run head public domain or IP?

### ISSUE THREAD

**Issue by cxnam** [mobz/elasticsearch-head#285]
I'm run elasticsearch-head as a standalone server, but do not public it. How to public elasticsearch-head via public domain or IP?

Thanks

**Comment by mobz** [comment]
elasticsearch-head running standalone is a web server. Elasticsearch is a separate server and BOTH must be public (for example running on AWS) and have CORS set up correctly, for them to be accessible publicly.

**Do not do this**
