### ISSUE TITLE
elasticsearch-shutdown

### ISSUE THREAD

**Issue by Lfengjie** [mobz/elasticsearch-head#289]
Hello:
        I try to shutdown the elasticsearch through the web UI of head plugin. But it is useless. why?

**Comment by mobz** [comment]
you'll need to provide the version of elasticsearch and any relevant logs

**Comment by Lfengjie** [comment]
Hello:

thank you for your reply!
ES version: 2.4
I use the head plugin.

There isn't any additional llog in the directory named logs. is it because I want to close the master node? So 
it will be faild.

**Comment by mobz** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/cluster-nodes-shutdown.html

I think this is the answer. The shutdown API has been removed from elasticsearch in version 2.1

**Comment by Lfengjie** [comment]
Thank you for your reply!
