### ISSUE TITLE
The state of cluster is not connected when I open http://localhost:9100/

### ISSUE THREAD

**Issue by 290315636** [mobz/elasticsearch-head#291]
I am run Elasticsearch-head as a standalone server and connect it to Elasticsearch 5.x.x.
But  the state of cluster is not connected when I open http://localhost:9100/

i am already started the ES successfully
![Uploading 327A2841-DF6B-4C93-8FC5-4297D0C03FBA.png…]()

**Comment by philipskokoh** [comment]
please check whether you have configured `http.cors.enabled` and `http.cors.allow-origin` or not

**Comment by 290315636** [comment]
@philipskokoh  thanks for your answer , but i am already configured that .

**Comment by philipskokoh** [comment]
Hmm.. Can you provide more details about your elasticsearch deployment? Is your elasticsearch running on the same machine? any other plugins or components installed? Any error messages shown?
btw, I cannot see your png file.

**Comment by 290315636** [comment]
i am just installed a new elasticsearch ,no other plugins or components installed! no error messages either.
both ES  and ES-head are installed in my PC.

**Comment by 290315636** [comment]
it maybe can not connect to the ES ,because the state same as when i stop ES.

**Comment by philipskokoh** [comment]
I just tested on my PC. Elasticsearch-head url is `localhost:9100`, and the elasticsearch-head connect to ES `localhost:9200`.
This screenshot connect elasticsearch-head to elasticsearch cluster 5.0.1
![es-head](https://cloud.githubusercontent.com/assets/3418824/20694317/5aaad8d2-b61f-11e6-93d0-326f5873b939.png)

**Comment by 290315636** [comment]
thanks very much ,i am configured  this http.cors.allow-origin : /http:\/\/localhost(:[0-9]+)?/

and  it worked !

**Comment by 290315636** [comment]
My profile : 
cluster.name : tikie
http.port : 9200
http.cors.enabled : true
http.cors.allow-origin : /http:\/\/localhost(:[0-9]+)?/
