### ISSUE TITLE
Dont work with Elasticsearch 5.0.1 

### ISSUE THREAD

**Issue by DBARUNNER** [mobz/elasticsearch-head#292]
I cant install it with elasticsearch 5.0.1 also dont work when i install it as stand alone sever 
could you help me how to install it ?

**Comment by philipskokoh** [comment]
It works in my machine.
Ensure that you have set `http.cors.enabled` and `http.cors.allow-origin`.

**Comment by jwoertink** [comment]
Yeah, I'm not getting it to work either. Installed as a standalone. Enabled the cors stuff in the config, and javascript console just says "XHR Error". Running macOS 10.12 on FireFox 50.

**Comment by philipskokoh** [comment]
@jwoertink: what's the value of your `http.cors.allow-origin`? You may not include elasticsearch-head ip address in that setting.

**Comment by jwoertink** [comment]
Ah, so it turns out that was it. I had `*` as the value. I changed it to `"*"` and it works now! That's the dumbest update I've ever had to do....
