### ISSUE TITLE
shutdown when ssh connection close

### ISSUE THREAD

**Issue by suclogger** [mobz/elasticsearch-head#297]
I'm running head as a standalone server with ES 5.0.2.
I tried to use `nohup grunt server &` command, but after closing my ssh connection, head is closed ;(
Have you an idea ? Like `grunt forever `?

**Comment by philipskokoh** [comment]
screen and nohup should be able to do it:
http://askubuntu.com/questions/8653/how-to-keep-processes-running-after-ending-ssh-session

**Comment by suclogger** [comment]
@philipskokoh `tmux` could do, thanks.
