### ISSUE TITLE
Create a webjar

### ISSUE THREAD

**Issue by ptahchiev** [mobz/elasticsearch-head#302]
It would be really awesome if this client was published as a webjar on webjars.org. This way we could also talk to the spring-boot guys to have as a separate endpoint to any spring-boot application that has elasticsearch as dependency.

**Comment by ptahchiev** [comment]
https://gitter.im/spring-projects/spring-boot/archives/2016/09/27

**Comment by mobz** [comment]
I'm sorry, I don't have an experience on how to publish something as a webjar. You can see a few contributions around docker recently. If you can submit a pull request for meta info or whatever is required, I'll look at it.

**Comment by ptahchiev** [comment]
I've created the webjar here:
https://github.com/webjars/webjars/issues/1750

**Comment by ptahchiev** [comment]
Closing this issue - the webjar is in Maven central.
