### ISSUE TITLE
Start server with custom ES endpoint

### ISSUE THREAD

**Issue by n1tr0g** [mobz/elasticsearch-head#303]
All,

I am not really familiar with node.js so maybe this is already possible, but when I start the server via `grunt server` is possible to pass an argument to define the ES where head will connect to. 

Now by default it's `http://localhost:9200`, but since ES 5.0.0 doesn't support site plugins anymore , this would simplify managing standalone instances of head.

**Comment by mobz** [comment]
https://github.com/mobz/elasticsearch-head#url-parameters this might help. But otherwise there is no way.

**Comment by n1tr0g** [comment]
Yeah saw that, however that means that when ppl are using head as an standalone server to monitor ES 5.0 they will need to bookmark the URL with the extra parameter or type it manually. 

If start argument would be supported would be really easy to spin up with docker specialized heads for different ES clusters. 

BTW would you approve an PR where this functionality would be added or via an extra argument or via an ENV variable ?

**Comment by mobz** [comment]
Yes, I would consider a PR for this. ENV variable would be the most user friendly I think? however the standalone server is still not the one making the requests to elasticsearch, the users browser (generally running outside docker) is making the requests. The standalone server (whether dockside or not) does not know anything about where the cluster is, only the browser.

building docker specialised heads for ES clusters would involve a proxy also I think.

I'm considering adding a proxy that would allow the standalone server to handle the requests to ES to fix this very issue, but it's not trivial

**Comment by n1tr0g** [comment]
OK make sense ... I will start with the ENV variable and let's see how it goes. This should fix my intermediate issue and improve the flexibility a bit.

Adding a proxy is most likely out of reach for me at the moment, due to my inexperience with node :)

**Comment by n1tr0g** [comment]
With my limited nodejs/javascript understanding the only way to implement an environment variable ES_HOST to replace the default value localhost:9200, would be to modify grunt server task to compile the code each time we start it. 

Would you be ok with a change like that ? Another alternative would be to implement a config file, but again we would need to modify the grunt server task.

**Comment by xzer** [comment]
this may be another option:

https://github.com/xzer/elasticsearch-plugin-hosting
