### ISSUE TITLE
when elasticsearch x-pack  is enabled head can't connnect

### ISSUE THREAD

**Issue by zqc0512** [mobz/elasticsearch-head#304]
when elasticsearch  5.1.2  x-pack  is enabled the xx.xx.xx.xx:9200 need logon can connect to es ,
but head  9100 can't connnect to xx.xx.xx.xx:9200, where to enturn the user and password for x-pack.

thanks.

**Comment by zqc0512** [comment]
how i can configure with elasticsearch-head

**Comment by mobz** [comment]
Hi, this is the place for raising bugs with elasticsearch-head, which this is not. There is lots of options for connecting elasticsearch 5.x and elasticsearch-head on the homepage of this project.

**Comment by zqc0512** [comment]
Hi mobz/elasticsearch-head:
i can't connect to es when the es x-pack is enabled,
when elasticsearch 5.1.2 x-pack is enabled the xx.xx.xx.xx:9200 need logon can connect to es ,
but head 9100 can't connnect to xx.xx.xx.xx:9200, where to enturn the user and password for x-pack.

      how do to solve it, thanks.
i  find the uri set   but  don't know how to set the username and password about x-pack. in url set. can give me a example. thanks.
.../elasticsearch-head/index.html?base_uri=http://cluster.example.com:9200/ where to set the password and user.







Thanks & Best Regards

周千财  Andy Zhou
===============================
电话：13581722147
E-mail: 13581722147@139.com
================================== 
免责声明：
本邮件及附件可能包涵专有信息或机密信息，未经授权，请勿针对本邮件内容进行任何更改或以任何方式传播、复制或派发。若您误收了不属您接收的邮件，请立即告知发件人并销毁您的电脑及网络上所有该邮件的相关信息，严禁直接或间接使用、泄露、传播或复印本邮件内容。
Declaration:
This Email and any attachments may contain confidential, proprietary or legally privileged information. You must not modify, disclose, distribute, or copy any part of this Email without authorization. If you receive this Email in error, please notify the sender immediately and delete this message and any copies from your computer and network. Any unauthorized usage, disclosure, distribution or copying, directly or indirectly, of any part of this Email is forbidden.


From: Ben Birch
Date: 2017-01-19 14:23
To: mobz/elasticsearch-head
CC: zqc0512; Author
Subject: Re: [mobz/elasticsearch-head] when elasticsearch x-pack is enabled head can't connnect (#304)
Hi, this is the place for raising bugs with elasticsearch-head, which this is not. There is lots of options for connecting elasticsearch 5.x and elasticsearch-head on the homepage of this project.

**Comment by mobz** [comment]
I'm not sure how authentication works for x-pack. Perhaps you can investigate and provide some information on what is missing here.

**Comment by zqc0512** [comment]
the connect need user name and password  
no use elasticsearch-head   it can connect in url usr http://username:password@xx.xx.xx.xx:9200/ this can connect to elasticsearch 5.1.2  
but use the elastisearch-head  there is can't input username and passowrd how can solve it .

**Comment by shadiakiki1986** [comment]
Same here. I was trying [elasticsearch-docker](https://github.com/shadiakiki1986/elasticsearch-docker/tree/fix_apk_pypip) which had x-pack enabled. Enabling CORS in `elasticsearch.yml` and passing in the "username/password" "elastic/changeme" as documented in [elasticsearch-head](https://github.com/mobz/elasticsearch-head#url-parameters) helped remove the "restricted access" error that I get without them, but it gives me an empty "XHR error" from [_site/app.js#1308](https://github.com/mobz/elasticsearch-head/blob/master/_site/app.js#L1308). As I couldn't figure out the problem, I just disabled `xpack` using [this](http://stackoverflow.com/a/39759753/4126114)

**Comment by hsj1606** [comment]
You need to add headers in elasticsearch.yml 
http.cors.allow-headers: Authorization
and passing url parameter like : http://192.168.38.59/es-head/?auth_user=elastic&auth_password=changeme

**Comment by mobz** [comment]
Thanks @hsj1606 I will add that info to the readme

**Comment by zqc0512** [comment]
I test like @hsj1606  use 9100 can connect to 9200 thanks..

**Comment by boroborome** [comment]
In my case I use this url to access head
http://192.168.100.100:9100/?auth_user=elastic&auth_password=changeme
and then use this url access elasticsearch
http://192.168.100.100:9200/
