### ISSUE TITLE
how to disable the automatic i18n feature?

### ISSUE THREAD

**Issue by xzer** [mobz/elasticsearch-head#307]
When I am using a browser which declare it is supporting the language that head is supporting too, the UI language of head will become the corresponding language.

Which may be good for some person, but it bothers me because  my working language of the elasticsearch related projects is English and I cannot even match the translated terms to the original English terms.

I want to know whether it is possible that to disable the automatic i18n at client side (I have no privilege to touch the server configuration)?

**Comment by mobz** [comment]
you can configure your browser to 'prefer' english rather than your native language. head respects whatever the browser tells it is your preferred language.

**Comment by xzer** [comment]
It is not so nice to change the browser's default language declaration only for elasticsearch usage since I will be using my native language for other situations.

But you advice suggested my that I may use a header modification plugin to change the header for elasticsearch only.

However, the above solution is just a workaround, and as a development tool, the correct way of i18n support is to allow users to choose which language they want to use, especially switching between English and local language.

I will try to create a PR to add the language switching feature to elasticsearch-head, which is acceptable? Or you think it is not necessary at all?

**Comment by mobz** [comment]
If you create a PR I would accept it. perhaps a query string param `lang=en` One problem (though not much) I use internal javascript number/date/time `toLocaleDateString` converter which is dependant on the locale settings of the browser. SO you might end up with english words but local formatting.
