### ISSUE TITLE
Param all all=true causing issues with ES 5.2

### ISSUE THREAD

**Issue by lokeshmadan** [mobz/elasticsearch-head#309]
Hi,

 I have installed ES 5.2 and everything works fine through command line. I installed elasticsearch-head (I have been using it as plugin since 2.x) following standalone server instructions. For some reason i was getting "cluster health: not connected" error. I tried debugging more and went to console. I found out 1 extra parameter "all=true" in below url.

http://localhost:9200/_nodes/stats?all=true

Please see attachment, response returns "request [/_nodes/stats] contains unrecognized parameter: [all]" . If i remove all=true from url, it seems to return some result. Any idea why we are adding that extra parameter.
<img width="1233" alt="screen shot 2017-02-01 at 10 36 35 pm" src="https://cloud.githubusercontent.com/assets/2107940/22539594/d4dbf87e-e8cf-11e6-915a-6c92146fa35f.png">

Not sure, if that's the issue which is causing above problem. 

BTW i have below config in elasticsearch.yml
http.cors.enabled: true
http.cors.allow-origin: "*"

**Comment by NicolJiang** [comment]
Same problem in my system, T-T.

**Comment by NicolJiang** [comment]
Problem of CORS：
vi ./bin/elasticsearch

Write the following lines: 
http.cors.enabled: true
http.cors.allow-origin: "*"

**Comment by NicolJiang** [comment]
vi config/elasticsearch.yml

Write the following lines:
http.cors.enabled: true
http.cors.allow-origin: "*"

**Comment by philipskokoh** [comment]
Hmmm... prior to Elasticsearch 2.4, we use `all=true`, Elasticsearch 2.4 and above use `/_nodes/stats/_all`. Actually, this parameter is not required. 

Reference:
1. https://www.elastic.co/guide/en/elasticsearch/reference/2.4/cluster-nodes-stats.html#_nodes_statistics
2. https://www.elastic.co/guide/en/elasticsearch/reference/2.3/cluster-nodes-stats.html#_nodes_statistics

**Comment by lokeshmadan** [comment]
@NicolJiang : Thanks for the reply. Please see my original request, i already have those settings in elasticsearch.yml.

**Comment by lokeshmadan** [comment]
@philipskokoh : Any idea, which file is adding that parameter. I can modify on my local.

**Comment by philipskokoh** [comment]
I just checked. It's solved in the latest version (see #276).
Update your ES-head, it should work.

**Comment by lokeshmadan** [comment]
Thanks. Seems to be working fine now.
