### ISSUE TITLE
accept server in query string

### ISSUE THREAD

**Issue by pgrisafi** [mobz/elasticsearch-head#311]
I like using elastichead in my own computer, and I have a nice bookmark like
file:///home/user/workspaces/elasticsearch-head/elasticsearch-head/index.html

However, I can not have different bookmarks for different clusters
I think it would be nice to have the option to write

file:///home/user/workspaces/elasticsearch-head/elasticsearch-head/index.html?cluster=http://server:8080

and have elasticsearchhead point and connect to http://server:8080 automatically

**Comment by mobz** [comment]
It already does this. Check the realm
