### ISSUE TITLE
Unable to connect: CORS issue- XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by deepakshrma** [mobz/elasticsearch-head#312]
--browser console.log
```
XMLHttpRequest cannot load http://localhost:9200/_all. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9100' is therefore not allowed access.
```
```
#env
window
elasticsearch-5.2.0
```

```

**Comment by mobz** [comment]
What is the CORS setup on the elasticsearch service?

**Comment by deepakshrma** [comment]
I was not aware of this options not mention in doc. Added paramers in elasticsearch.yml. working fine. only issue in dashbord page.

```yml
#~\elasticsearch-5.2.0\config\elasticsearch.yml
http.cors.enabled: true
http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/
```

Dashbord console.log(when you enter url and hit connect button):
```
Uncaught TypeError: Cannot read property 'toString' of undefined
    at nodeSort_addr (http://localhost:9100/_site/app.js:3347:91)
    at Array.sort (native)
    at Class.draw_handler (http://localhost:9100/_site/app.js:3586:6)
    at http://localhost:9100/_site/app.js:351:15
    at Array.forEach (native)
    at Class.fire (http://localhost:9100/_site/app.js:350:34)
    at Class.updateModel (http://localhost:9100/_site/app.js:1347:11)
    at Object.success (http://localhost:9100/_site/app.js:1386:17)
    at Object.resolveWith (http://localhost:9100/_site/vendor.js:995:27)
    at done (http://localhost:9100/_site/vendor.js:7128:14)
```
![Dashborad img](https://lh3.googleusercontent.com/xIjlaoxrYZUp_v8PNXAfqhWwq2kAS5CulsH3QAvda-qASBe-JzG6xXrhNyiF7oCFUljztw7GKfjjxbVhetiQ5NnJLPvn-quDm0-V0F-5Un-2kAp0jd8LHgC3TmO8CyQujsP98dl-HQV5nKES4xzvPT7E8f3LPGuuIRr5VOH1_L30JHSO3zey1usu2tCe0GkRn7KgkSAe7VOKvchZAMKgJ5KxiJeDCHhNqqPVhfBRh6xsMkBLNvtKLbHoDapF1-Axh7dKYriAVMHGHS-cExwhl9pIyopJmKdbfqKxyV8vEUbY_XhLh2OI9N7eXFzdMianXQ7aOLmQOy3jdqxK54FuwX-1kZLgaYeeQtO658M-XyMjVEBk3VPT5hAyKmDip3jTzRnRANIuXLaiZJDKB4KWuw5hOtlCh3kWETQATUzgXUZTe8jgIJ09pDfxTfXzTgrvjvPOvNz2P27aYsvOiVTDS_oNhHlo7u-uZpoD2cYyZiLNP3r56-nSGFd0Z1A89DhAWjrG3vfpHGJAEfRXmlFxneKY2e0wixO8xSX2CnHG_OdERM34q475d42N8XxpBu2H7bN_Ghnw=w1600-h753)
