### ISSUE TITLE
Overview not working with elasticsearch 5.2

### ISSUE THREAD

**Issue by 2arunpmohan** [mobz/elasticsearch-head#314]
Overview is not getting shown in the UI.
The cluster overview pane was not showing anything. Upon inspecting I found the below in Chrome console.
![elasticsearch_head_issue](https://cloud.githubusercontent.com/assets/9315301/23034718/b6f8783a-f4a2-11e6-9353-771506c7d0cb.png)

 When I removed "?all=true" part from the code (line number 1327 of elasticsearch-head/_site/app.js and line number 38 of elasticsearch-head/src/app/services/clusterState/clusterState.js), it was solved. Dont know if it breaks something. Please have a look.

**Comment by philipskokoh** [comment]
Fix on #276. Please update your elasticsearch-head to latest version.
