### ISSUE TITLE
Where is the configuration file?

### ISSUE THREAD

**Issue by mslee89** [mobz/elasticsearch-head#318]
The following options may not need to be placed anywhere.

http.cors.enabled: true
http.cors.allow-origin: "*"

Could you tell me the location?

I am using ElasticSearch_Head for ElasticSearch 5.2.2

**Comment by mobz** [comment]
Hi, github issue are for reporting bugs with code, not for getting help. You should ask questions on a forum such as this one: https://discuss.elastic.co.
