### ISSUE TITLE
query_string don't return any results

### ISSUE THREAD

**Issue by AI-PaaS** [mobz/elasticsearch-head#319]
ES clasuter 2.3.3 with head. I created three index. when I use Structured Query [+], select the index filed, then select query_string, then input search word, after i click search button, there is no result displayed. I display the query string, like this: {
"query": {
"bool": {
"must": [
{
"query_string": {
"default_field": "mgmt-chl-index.channelname",
"query": "渠道"
}
}
],
"must_not": [ ],
"should": [ ]
}
},
"from": 0,
"size": 10,
"sort": [ ],
"aggs": { }
}
If i copy and paste in the any request. and remove "mgmt-chl-index.channelname" as "channelname", the result is ok!

**Comment by philipskokoh** [comment]
Can you help to confirm the syntax of query_string?
It seems that ES do not accept index type in the query field anymore..

**Comment by philipskokoh** [comment]
It's fixed now. Thanks for informing!
