### ISSUE TITLE
es index size (195Mi) is lager greater  than the log file in server(27M) ,why 195Mi vs 27M

### ISSUE THREAD

**Issue by linfanli** [mobz/elasticsearch-head#331]
![2017-04-26 3 37 56](https://cloud.githubusercontent.com/assets/16367420/25425843/d675e17e-2a9f-11e7-9003-97e9e6bdc7d3.png)

the log file in serve is 27M, the ES index size is 195M, why?
I created an index called "ofbiz168",as show in the attach png,the front page of the head plugin, it shows:
ofbiz168
size: 195Mi (390Mi)
docs: 681,144 (1,362,388)

there is [issue 264](https://github.com/mobz/elasticsearch-head/issues/264) about incorrect size number but is nothing about the file in sever(input data)

**Comment by mobz** [comment]
Not sure what "log file in serve is 27M" means (perhaps this is your source of data?), but the size relates to the amount of disk used to store the raw data _and indices_. 'head simply returns the data reported by your cluster. more info: https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html

**Comment by philipskokoh** [comment]
@linfanli: the size of an index really depends on your index mapping. More complex data types such as geo-point, and nested objects  may require more disk space to store.

**Comment by linfanli** [comment]
@mobz yes ,"log file in serve is 27M" means the source data,
