### ISSUE TITLE
how to get it working with cluster secured with search gaurd ?

### ISSUE THREAD

**Issue by prabumohan** [mobz/elasticsearch-head#336]
https://admin:admin@localhost:9200 work ok from my browser with a ssl exception. how to i get elasticseach-head working ?  has anyone tried it before ?

**Comment by philipskokoh** [comment]
Simplest way, use URL parameter:
https://github.com/mobz/elasticsearch-head#url-parameters

**Comment by prabumohan** [comment]
Hi , Tried with your parameters option it works only for x-pack not with Serach -gaurd . If you could help with search gaurd that would be great !
