### ISSUE TITLE
Safari 11 throwing DOM Exception 18.  I believe it's due to localStorage.

### ISSUE THREAD

**Issue by TheZeke** [mobz/elasticsearch-head#344]
Getting an error using Safari 11.  Is there some way around this by changing Safari somehow?  I looked through the configuration of Safari 11 but found no options that would make an exception for ./elasticsearch-head/.  Would hosting it on a web server instead of opening it locally work?

**Browser:** Version 11.0 (12604.1.28.2)
## To Replicate:
```$ git clone https://github.com/mobz/elasticsearch-head/
Cloning into 'elasticsearch-head'...
remote: Counting objects: 4067, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4067 (delta 0), reused 2 (delta 0), pack-reused 4063
Receiving objects: 100% (4067/4067), 2.10 MiB | 479.00 KiB/s, done.
Resolving deltas: 100% (2222/2222), done.
$ cd elasticsearch-head/ ; open index.html
```

## Error:
**URL:** file:///Users/<myusername>/elasticsearch-head/index.html
```
[Error] SecurityError (DOM Exception 18): The operation is insecure.
	init (app.js:1242)
	Class (app.js:265)
	instance (app.js:380)
	init (app.js:4328)
	(anonymous function) (app.js:281)
	Class (app.js:265)
	onload (index.html:21)
```

## Line 1242:
Line 1242 of app.js is within the stanza below:
```
    services.Preferences = ux.Singleton.extend({
        init: function() {
            this._storage = window.localStorage;  <------ line 1242
            this._setItem("__version", 1 );
        },
```

**Comment by mobz** [comment]
you will need to run a local fileserver, for example the built in one using node or someother
