### ISSUE TITLE
in browser-tab up and down keys not working

### ISSUE THREAD

**Issue by ralfuslongus** [mobz/elasticsearch-head#348]
In a older version in the browser-tab you could select one document (the documents details opens up), then, by pressing up or down, the previous or next document was selected and shown in the already open details-window. In the current version nothing happens, just the selection disappears and, if you have the firefox-web-console open, there appears an error saying something like "error: this.el is null in app.js line 1453". Here is the line:

`this.el.remove();` <- (you could get an NullPointerException in java here)

I just hotfixed it by inserting a not-null-check:

`if (this.el != null) { this.el.remove();}`

I am very surprised that nobody else reported this error before, it is very obvious and easy to find, even for an _never-coded-javascript-or-any-other-web-shit-before-programmer_ like me:-). I use head a lot (thank you very much mobz) and it has bothered me a long time now.

Hope this helps
Greetings
ralfuslongus

**Comment by philipskokoh** [comment]
Fixed, thanks!
