### ISSUE TITLE
 Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header

### ISSUE THREAD

**Issue by nice2mu** [mobz/elasticsearch-head#352]
Content type detection for rest requests is deprecated. Specify the content type using the [Content-Type] header

 ss_deprecation.log

**Comment by zhaowawj** [comment]
Yeah! I'm using elasticsearch-6.0.0-beta1, found that I can't use elasticsearch-head directly, need to modify these things:
1. modify elasticsearch config: config/elasticsearch.yml, add
```yml
http.cors.enabled: true 
http.cors.allow-origin: "*"
```
2. modify elasticsearch-head source: specify contentType
https://github.com/mobz/elasticsearch-head/blob/master/_site/app.js#L1300
```js
request: function( params ) {
        return $.ajax( $.extend({
                url: this.base_uri + params.path,
                contentType: "application/json;charset=UTF-8",
                dataType: "json",
                error: function(xhr, type, message) {
                        if("console" in window) {
                                console.log({ "XHR Error": type, "message": message });
                        }
                }
        },  params) );
},
```

**Comment by philipskokoh** [comment]
Thanks for reporting!

**Comment by liqinglin06** [comment]
Thanks for reporting!
