### ISSUE TITLE
Standalone server is not able to connect to external ES domain

### ISSUE THREAD

**Issue by realjam** [mobz/elasticsearch-head#354]
I followed the steps to containerize the ES head and trying to connect to external elasticsearch cluster that is using Basic auth of Username and password. In the text tab i have given **https://Username:Password@ESDomain** but it not able to connect and in the debugger console I am getting  this:
> Failed to load resource: the server responded with a status of 401 (Unauthorized)

### Expected behaviour 
Whenever the full URL given( with username and password embedded) in the text tab, it need to connect to ES cluster and fetch the result as it working with chrome extension.

### Actual Behaviour

**1.**  Whenever the full URL given( with username and password embedded) in the text tab, it haven't connected to ES cluster and logged this:
> Failed to load resource: the server responded with a status of 401 (Unauthorized)

**2.** Tried by giving URL parameter `base_uri`, `auth_user` and `auth_password` but still no luck and then it logged this:
> Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

### Step to Reproduce
Create new docker image using `Dockerfile-alpine` file and run it on port 9100.
Access the external Elasticsearch cluster that is using basic auth of Username and password.

**Comment by philipskokoh** [comment]
Use url parameter auth_user and auth_password to connect:
https://github.com/mobz/elasticsearch-head#x-pack

**Comment by realjam** [comment]
Tried with `base_uri`, `auth_user` and `auth_password` in URL parameter but it was logging this:

> Authorization is not allowed by Access-Control-Allow-Headers in preflight response.

**Comment by philipskokoh** [comment]
Hmm. it should work.
did you set `http.cors.enabled`, `http.cors.allow-origin`, and `http.cors.allow-headers` in elasticsearch.yml?

**Comment by realjam** [comment]
This is what i got from `elasticsearch.yml` file
```
http.cors.enabled: true
http.cors.allow-origin: *
```
Apparently I didn't find any entry for `http.cors.allow-headers`. It's strange that chrome extension is working perfectly with current elasticsearch configuration but not with standalone server.

**Comment by philipskokoh** [comment]
set `http.cors.allow-headers: Authorization`
https://github.com/mobz/elasticsearch-head#basic-authentication

**Comment by realjam** [comment]
Thanks. It's now working
