### ISSUE TITLE
Can not search in Elasticsearch 6

### ISSUE THREAD

**Issue by weberhofer** [mobz/elasticsearch-head#361]
Elasticsearch 6 is not auto-detecting the content type. It must be set correctly. Searching in EL6 currently results in:
```
{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}
```
Sending the content as "application/json" would fix that issue.

**Comment by zhouyongtao** [comment]
I also encountered the same problem

**Comment by vqiu** [comment]
me too

**Comment by llonchj** [comment]
+1

**Comment by sapanparikh18** [comment]
+1

**Comment by gusfot** [comment]
I modified source file. "_site/app.js"
1310                         },  params) );
=> 1310:                         },  JSON.Stringfy(params)) );

**Comment by liar666** [comment]
Would be great if the modification could be integrated in the main code so that everyone can benefit from it. @gusfot can you make it a pull request?
Indeed, since the "offical"/mobz, docker image is not compatible with 6.0.0, I'm using a docker image that pulls the code from the git repo... Would be great if that one could work too

**Comment by gusfot** [comment]
@liar666 Thanks! O.K.^^

**Comment by liar666** [comment]
BTW, its JSON.**s**tring**i**fy(params) and it did not solve the problem here :{

I'm using the whole ELK 6.0.0 stack and monitoring with Head using a docker image that pulls the latest git code:
docker run --net=host -it --name "monitoring" salgat/elasticsearch-head

Changing the line you indicate made my "Any request" tab change its behaviour, but it still does not work. It now froze on:
"Requesting..."
instead of getting the error:
`[application/x-www-form-urlencoded] is not supported`.

Also, clicking on "connect" next to "http://localhost:9200/" still does nothing :{ Probably the same problem with JSON not being explicitely required...

**Comment by AhmyOhlin** [comment]
I installed ES6.0 and head ES .
I am able to see my index but i can't see the docs. When i do search, i get nothing.
Any clue how to fix it?

**Comment by Feliksas** [comment]
I fixed it by adding headers["Content-Type"] = "application/json"; to vendor.js at line 7819

**Comment by AhmyOhlin** [comment]
@Feliksas  at line 7819  i tried to add the line   as you said headers["Content-Type"] = "application/json";  
but it make the whole Head ES not working

**Comment by AhmyOhlin** [comment]
@liar666  does navigation tabs work ?

**Comment by liar666** [comment]
Not sure what you call Navigation Tabs, but here is what I get on a dummy cluster:
https://i.imgur.com/KLVEJcV.png
https://i.imgur.com/l4KYhKq.png
https://i.imgur.com/A6Ys0EW.png
https://i.imgur.com/PmB56ee.png
https://i.imgur.com/Vz2dr39.png

**Comment by priteshkp** [comment]
I also made a similar change to fix this issue in the Chrome plugin that uses ES-head:
https://github.com/TravisTX/elasticsearch-head-chrome/pull/6

**Comment by vohtaski** [comment]
will there be an official release with the fix for ES v6.0.0?

**Comment by AhmyOhlin** [comment]
i reinstalled the ES-head Chrome plugin. Now it  works fine

**Comment by lyk2112** [comment]
at line 6886  replace with contentType: "application/json" it works.

**Comment by zouyx** [comment]
no problem in ES 6.0.1

**Comment by Hananeee** [comment]
Hellooo , i've started learning how elasticsearch works and i've encountered this problem while trying to add a document (ps: i'm following the steps mentioned on a tutorial ), i need help pls :
C:\WINDOWS\system32>curl -X PUT "localhost:9200/customer/_doc/1?pretty" -H 'Content-Type: application/json' -d'
{
"error" : "Content-Type header [application/x-www-form-urlencoded] is not supported",
"status" : 406
}
curl: (6) Could not resolve host: application

**Comment by philipskokoh** [comment]
This problem has been fixed before. 
Reference: https://github.com/mobz/elasticsearch-head/commit/5a81d758e97db7c7e9ba3a4c0c82a2be5e448029

Please update es-head to latest version if you encounter the problem.

**Comment by elixiao** [comment]
> This problem has been fixed before.
> Reference: [5a81d75](https://github.com/mobz/elasticsearch-head/commit/5a81d758e97db7c7e9ba3a4c0c82a2be5e448029)
> 
> Please update es-head to latest version if you encounter the problem.

However, the official docker image has not update to latest version. I have to manually add code `contentType: "application/json",` to files 

- `_site/app.js` 
- `src/app/services/cluster/cluster.js`. 

just before `dataType: "json"`. My docker image is mobz/elasticsearch-head:5-alpine.

**Comment by tsrivishnu** [comment]
If anyone is interested, I forked this repo to build and push the updated docker images with the fix for this issue along with others. https://hub.docker.com/repository/docker/tsrivishnu/elasticsearch-head

**Comment by tsrivishnu** [comment]
@viktorianer Turns out, I put the wrong link. Here is the correct one: https://hub.docker.com/r/tsrivishnu/elasticsearch-head/tags

Notice that I don't have a `latest` tag

**Comment by viktorianer** [comment]
@tsrivishnu thank you for your support.
But, why is the original image never updated (`mobz/elasticsearch-head:5`)?

**Comment by Jimmea** [comment]
I also encountered the same bug in docker-compose using Elasticsearch 7x. Please update for ES 7X @mobz

**Comment by lsqtongxin** [comment]
elasticsearch-head/_site/vendor.js line 6886 and line 7573
revise the elasticsearch  elasticsearch.yml，add content-type

http.cors.allow-headers: Authorization, Content-Type
