### ISSUE TITLE
Differences in results depening on view

### ISSUE THREAD

**Issue by schmalle** [mobz/elasticsearch-head#372]
HI, I really like your tool. actually I use the chrome plugin on mac. When I look at an index via the Index browser i see different results when viewing on the request pane (see attached pictures).
Dont know, if this is an ES issue (i run 5.6.4) but wanted to report it.
Thanks once more the great tool.
Best wishes
Markus

![2](https://user-images.githubusercontent.com/1190164/32701528-edc6d862-c7d7-11e7-8f32-2d0a3c5991da.jpeg)
![1](https://user-images.githubusercontent.com/1190164/32701527-e8799afc-c7d7-11e7-909e-d324a0a60271.jpeg)

**Comment by philipskokoh** [comment]
You search on one index at structured query, whereas you search on all indices at browser view. That explains the difference.
