### ISSUE TITLE
plugin head cant access localhost 9200

### ISSUE THREAD

**Issue by louiegit** [mobz/elasticsearch-head#381]
hello,I'm gonna start plugin head,but something wrong happened,I found logs in console:

Failed to load http://localhost:9200/_cluster/health: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:9100' is therefore not allowed access.

**Comment by shubaivan** [comment]
add to `/etc/elasticsearch/elasticsearch.yml`
`http.cors.enabled: true
http.cors.allow-origin: "*" is `
