### ISSUE TITLE
Cannot Search or Browse documents with ES 6.3.1

### ISSUE THREAD

**Issue by GHGautamGH** [mobz/elasticsearch-head#396]
Hi,

I am using Elasticsearch-head GUI to connect/browse my ES cluster. Recently I upgraded to version 6.3.1 from v5.3.1 and since then I cannot view the documents in the Browser tab. Nor can I search documents using Structured Query tab. 

Can you please help?

Thanks.

**Comment by philipskokoh** [comment]
Hi, I did a quick test on ES 6.3.1. It seems ok at my side. Can you elaborate more on how you run Elasticsearch-head?
![screenshot from 2018-07-25 10-09-13](https://user-images.githubusercontent.com/3418824/43175699-f534044c-8ff2-11e8-9de9-69e17a3c32f4.png)

**Comment by GHGautamGH** [comment]
Hi Philips,

Thanks for replying. The problem has been solved after I used Google Chrome Extension Plugin.

REgards/Gautam
