### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by breisig** [mobz/elasticsearch-head#397]
Hello,

Is this project dead? It seems the last commit was over 10 months ago and there are a bunch of pull requests that are sitting in a queue [Like the ES 6.xx search support].

**Comment by philipskokoh** [comment]
Hi @breisig , current Elasticsearch-head is able to connect to ES 6.xx. Do you have any problems connecting to ES 6 using Elasticsearch-head?

**Comment by Wing924** [comment]
ES6 requires correct Content-Type.

`{"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}`

**Comment by philipskokoh** [comment]
Hi @Wing924 ,  can you elaborate on how you get this error message? Which queries or functions / components give you that error message?

All Elasticsearch-head requests are sent using this function which specify `contentType: "application/json"`. See the code below:

https://github.com/mobz/elasticsearch-head/blob/bee08506a964c1bff32c7be9c0b219a728f2704d/src/app/services/cluster/cluster.js#L30-L40

I believe the specified parameter `contentType: "application/json"` overrides default `application/x-www-form-urlencoded` parameter in jquery.

I did few tests on multiple Elasticsearch 6.x.x. Elasticsearch-head looks ok at my side.
![es6-req_contenttype](https://user-images.githubusercontent.com/3418824/43235342-0c45d4f6-90b3-11e8-84c0-27fc9459eb63.png)

**Comment by Wing924** [comment]
@philipskokoh I found my elasticsearch-head is outdated. I updated it and works fine. Thank you. :)
