### ISSUE TITLE
How to know  some node health status in cluster?

### ISSUE THREAD

**Issue by pengjinfeng1024** [mobz/elasticsearch-head#399]
I can know nodes in cluster health status by head front web plugin
but I want know nodes in cluster health status by instrcution, such as “/_cat/nodes”
like my cluster has three nodes, if one of they nodes down or not work

**Comment by philipskokoh** [comment]
Hi, 
there are two places where you can check node stats. See screenshot below. However, if a machine is down, and leaves the cluster, you won't see that particular node listed in the cluster.
![screenshot from 2018-09-19 18-57-48](https://user-images.githubusercontent.com/3418824/45749497-68614700-bc3e-11e8-9fff-491d90cc0345.png)
![screenshot from 2018-09-19 18-58-29](https://user-images.githubusercontent.com/3418824/45749498-68614700-bc3e-11e8-831c-07a21e3d4026.png)

**Comment by mobz** [comment]
@philipskokoh I wonder if we should start using the wiki feature of github? There are many questions about how to connect etc, and things like this is a great answer, that might get lost if not moved somewhere with more visibility? Also, you are a gentleman and a scholar. 💯

**Comment by pengjinfeng1024** [comment]
thanks for your help, i know check node health status by head web plugin. 
Do you konw another method ? like instruction . such as "/_cat/nodes". just an instruction? thanks!

**Comment by pengjinfeng1024** [comment]
@philipskokoh alright. thanks guys!
