### ISSUE TITLE
Fail to sort nodes by address when there are unassigned shards

### ISSUE THREAD

**Issue by Starwalker2000** [mobz/elasticsearch-head#407]
When there are unassigned shards, a virtual node has only name attribute in cluster is created. But there is no transport_address attribute when sorting nodes by address.

Check `nodeSort_addr( a, b )` function in `app.js`. The following line:

> return a.cluster.transport_address.toString().localeCompare( b.cluster.transport_address.toString() );

a.cluster has no transport_address attribute at all when a is the virtual node of unassigned shards.

**Comment by philipskokoh** [comment]
Can you provide the steps to reproduce the issue? I have a problem to reproduce it.

**Comment by Starwalker2000** [comment]
Yep. Just connect to an ES server which has unassigned shards with Elasticsearch Head app of chrome. Then sort cluster nodes by address and connect again. The shards and nodes disappear.

Check the console of chrome. You'll get following:
> Uncaught TypeError: Cannot read property 'toString' of undefined
>     at nodeSort_addr (app.js:3347)
>     at Array.sort (<anonymous>)
>     at Class.draw_handler (app.js:3588)
>     at app.js:351
>     at Array.forEach (<anonymous>)
>     at Class.fire (app.js:350)
>     at Class.updateModel (app.js:1346)
>     at Object.success (app.js:1352)
>     at Object.resolveWith (vendor.js:995)
>     at done (vendor.js:7128)

**Comment by philipskokoh** [comment]
Fixed now via https://github.com/mobz/elasticsearch-head/commit/bee08506a964c1bff32c7be9c0b219a728f2704d
Thanks for reporting! Please update your elasticsearch-head to latest version.
