### ISSUE TITLE
npm install error,can't download phantomjs

### ISSUE THREAD

**Issue by codertutu** [mobz/elasticsearch-head#414]
when i run npm install,the error is below
i find this url is 404,how can i solve it?
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2

**Comment by philipskokoh** [comment]
what is the error message?

**Comment by codertutu** [comment]
i tried yesterday,it seems ok.
