### ISSUE TITLE
Is there any plan to support es 7.x ?

### ISSUE THREAD

**Issue by hellxz** [mobz/elasticsearch-head#418]
i just want to know about it. can somebody tell me ?

**Comment by philipskokoh** [comment]
any problems running it on es 7.x?

**Comment by Backgammon-** [comment]
The response format for hit count has changed so it doesn't display properly in head; probably some other minor things. Easy fixes, but it's still work.

**Comment by HellxZ** [comment]
not problem with es7.1, because i haven't try it . i use docker for create cluster and can't find a es-head for 7.x.
I just see this hub not contain the support for es6 and es7，and yesterday i have try to use es-head google-chrome plugin. seems the hit count does not display .

**Comment by philipskokoh** [comment]
I just push an update to handle 'hit count' for ES 7.x. The latest code should support ES 7.x now.
Thanks for reporting about 'hit count' breaking issue!
