### ISSUE TITLE
Unable to connect elasticsearch server via https

### ISSUE THREAD

**Issue by orest-gulman** [mobz/elasticsearch-head#429]
I'm unable to connect Elasticsearch server via https, I didn't find in the documentation information about it, does elasticsearch-head support https?

**Comment by orest-gulman** [comment]
Apologies, it was my mistake.

**Comment by slan77** [comment]
@orest-gulman,  Could you share the method that how to connect to  Elasticsearch server via https? I have the same issue now. Thanks!

**Comment by orest-gulman** [comment]
hi @slan77, I just enter the full domain name of my server [https://myelasticsearch.domain:9200] then credentials and that it, sometimes it takes a long time to connect (15-20sec).

**Comment by slan77** [comment]
Thanks, I will try.
