### ISSUE TITLE
the branches:master/1.x/0.9 cannot find the search.yaml or  elasticsearch.yml

### ISSUE THREAD

**Issue by eilinge** [mobz/elasticsearch-head#430]
I want to connect to the cluster, it needs to add 'http.cors.enabled: true; http.cors.allow-origin: "*"', but I did not find the configuration file

**Comment by eilinge** [comment]
![Screenshot from 2019-12-07 16-23-34](https://user-images.githubusercontent.com/38291074/70371451-348b4380-190e-11ea-9096-9134c53eea07.png)
where is the config file?

**Comment by philipskokoh** [comment]
Hi @eilinge, 
the elasticsearch configuration is under `/etc/elasticsearch` or `/etc/default/elasticsearch` (for the Debian package) or `/etc/sysconfig/elasticsearch` (for the RPM package). Please check your Elasticsearch installation.

Reference:
https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html

**Comment by eilinge** [comment]
@philipskokoh  tks.  Find the yaml.conf by using the RPM package
