### ISSUE TITLE
在使用x-pack的情况下账号密码必须使用明文吗？

### ISSUE THREAD

**Issue by zachzzq** [mobz/elasticsearch-head#435]
在使用x-pack的情况下，使用head就必须使用明文访问。出于安全考虑这事绝对不行的啊。请问有什么解决办法吗？ 或者后续会有新的解决办法吗？

**Comment by philipskokoh** [comment]
At the moment, no security mechanism for elasticsearch-head.
For more complete solution, you can use Elastic Stack which includes Kibana.
