### ISSUE TITLE
es haed插件主页两个分片数量分别代表什么

### ISSUE THREAD

**Issue by tugangkai** [mobz/elasticsearch-head#436]
es haed插件主页两个分片数量分别代表什么，我的es集群，这两个分片数量不一致，左边小于右边，导致es写入没有响应。

**Comment by philipskokoh** [comment]
Sorry, I can't fully understand your question. Which number are you refering to?

**Comment by tugangkai** [comment]
![微信图片_20200603170459](https://user-images.githubusercontent.com/11631151/83618178-a7732f80-a5bc-11ea-9997-da2fb4c59bcd.png)
右边绿色框两个数字

**Comment by tugangkai** [comment]
head插件 上集群健康值: green(1461 of 1462)

**Comment by philipskokoh** [comment]
(<current active shards> of <total shards>)
If the one at the left side is less than total shard, then some index shards have not started yet. It could be because some nodes are down.

**Comment by tugangkai** [comment]
节点都正常，你这说的不对。我是想知道head插件是怎么得到这个值的

**Comment by philipskokoh** [comment]
Elasticsearch-head reads data from Elasticsearch Cluster APIs. 
Cluster health and cluster state API, if I remember correctly

**Comment by tugangkai** [comment]
这个我也知道，我是想知道具体细节

**Comment by philipskokoh** [comment]
After running and debugging the code, I found out that those numbers come from indices stats.

This are the section to show the numbers. Shards is taken from status inside clusterState.
https://github.com/mobz/elasticsearch-head/blob/d0a25608854479f0b3f2dca24e8039a2fd66b0e2/src/app/ui/header/header.js#L48-L56

Looking more detail inside clusterState, this variable is coming from `_stats`.
https://github.com/mobz/elasticsearch-head/blob/d0a25608854479f0b3f2dca24e8039a2fd66b0e2/src/app/services/clusterState/clusterState.js#L60-L63

One field in the indices stats response gives us this information.
`_shards":{"total":10,"successful":5,"failed":0},`
Total indicates total number of shards, successful indicates the number of active shards.

Reference about indices stats:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-stats.html

Hope it helps.  :)
