### ISSUE TITLE
我在安装npm run 时，报错

### ISSUE THREAD

**Issue by songsh** [mobz/elasticsearch-head#437]
npm run ： 提示， 是什么意思?
![image](https://user-images.githubusercontent.com/2272252/86313570-05487500-bc58-11ea-80e2-7818296f123c.png)

**Comment by philipskokoh** [comment]
I am not familiar with windows, but I think you need to install node.js first.
https://nodejs.org/en/

**Comment by songsh** [comment]
我装node , cmd 运行node -v 有返回

**Comment by philipskokoh** [comment]
Following this guide https://github.com/mobz/elasticsearch-head#running, 
it should be `npm run start`.

**Comment by songsh** [comment]
sorry.
