### ISSUE TITLE
Cluster health value: not connected

### ISSUE THREAD

**Issue by pphanwang** [mobz/elasticsearch-head#438]
win 10
Elasticsearch 7.8.0 
java 1.8 
npm 6.14 
grunt-cli v1.3.2
grunt v1.0.1
Elasticsearch was successfully installed before installing elasticsearch head
I deploy on a local stand-alone basis ， this is my seting 
##########################################################################################
Gruntfile.js
module.exports = function(grunt) {

	var fileSets = require("./grunt_fileSets.js");

	// Project configuration.
	grunt.initConfig({
		clean: {
			_site: {
				src: ['_site']
			}
		},
		concat: {
			vendorjs: {
				src: fileSets.vendorJs,
				dest: '_site/vendor.js'
			},
			vendorcss: {
				src: fileSets.vendorCss,
				dest: '_site/vendor.css'
			},
			appjs: {
				src: fileSets.srcJs,
				dest: '_site/app.js'
			},
			appcss: {
				src: fileSets.srcCss,
				dest: '_site/app.css'
			}
		},

		copy: {
			site_index: {
				src: 'index.html',
				dest: '_site/index.html',
				options: {
					process: function( src ) {
						return src.replace(/_site\//g, "");
					}
				}
			},
			base: {
				expand: true,
				cwd: 'src/app/base/',
				src: [ '*.gif', '*.png', '*.css' ],
				dest: '_site/base/'
			},
			iconFonts: {
				expand: true,
				cwd: 'src/vendor/font-awesome/fonts/',
				src: '**',
				dest: '_site/fonts'
			},
			i18n: {
				src: 'src/vendor/i18n/i18n.js',
				dest: '_site/i18n.js'
			},
			lang: {
				expand: true,
				cwd: 'src/app/lang/',
				src: '**',
				dest: '_site/lang/'
			},
			chrome: {
				src: 'src/chrome_ext/*.*',
				dest: '_site/'
			}
		},

		jasmine: {
			task: {
				src: [ fileSets.vendorJs, 'src/vendor/i18n/i18n.js', 'src/app/lang/en_strings.js', fileSets.srcJs ],
				options: {
					specs: 'src/app/**/*Spec.js',
					helpers: 'test/spec/*Helper.js',
					display: "short",
					summary: true
				}
			}
		},

		watch: {
			"scripts": {
				files: ['src/**/*', 'test/spec/*' ],
				tasks: ['default'],
				options: {
					spawn: false
				}
			},
			"grunt": {
				files: [ 'Gruntfile.js' ]
			}
		},

		connect: {
			server: {
				options: {
					hostname: "0.0.0.0",
					port: 9100,
					base: '.',
					keepalive: true
				}
			}
		}

	});

	grunt.loadNpmTasks('grunt-contrib-clean');
	grunt.loadNpmTasks('grunt-contrib-concat');
	grunt.loadNpmTasks('grunt-contrib-watch');
	grunt.loadNpmTasks('grunt-contrib-connect');
	grunt.loadNpmTasks('grunt-contrib-copy');
	grunt.loadNpmTasks('grunt-contrib-jasmine');

	// Default task(s).
	grunt.registerTask('default', ['clean', 'concat', 'copy', 'jasmine']);
	grunt.registerTask('server', ['connect:server']);
	grunt.registerTask('dev', [ 'default', 'watch' ]);

};
######################################################################
elasticsearch.yml

http.cors.enabled: true
http.cors.allow-origin: "*"

network.host: myip
#######################################################################

I have found many ways on the Internet, 
but I can't connect successfully. I want to seek your help.
 thank you

**Comment by philipskokoh** [comment]
Do you see any errors, if you follow these steps: https://github.com/mobz/elasticsearch-head#running-with-built-in-server

**Comment by pphanwang** [comment]
have no&nbsp;errors&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Philips Kokoh"<notifications@github.com&gt;; 
发送时间: 2020年7月5日(星期天) 晚上7:05
收件人: "mobz/elasticsearch-head"<elasticsearch-head@noreply.github.com&gt;; 
抄送: "474735625"<474735625@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mobz/elasticsearch-head] Cluster health value: not connected (#438)





 
Do you see any errors, if you follow these steps: https://github.com/mobz/elasticsearch-head#running-with-built-in-server

**Comment by pphanwang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Philips Kokoh"<notifications@github.com&gt;; 
发送时间: 2020年7月5日(星期天) 晚上7:05
收件人: "mobz/elasticsearch-head"<elasticsearch-head@noreply.github.com&gt;; 
抄送: "474735625"<474735625@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mobz/elasticsearch-head] Cluster health value: not connected (#438)





 
Do you see any errors, if you follow these steps: https://github.com/mobz/elasticsearch-head#running-with-built-in-server

**Comment by pphanwang** [comment]
&nbsp; thank you&nbsp; Problem solving.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Philips Kokoh"<notifications@github.com&gt;; 
发送时间: 2020年7月5日(星期天) 晚上7:05
收件人: "mobz/elasticsearch-head"<elasticsearch-head@noreply.github.com&gt;; 
抄送: "474735625"<474735625@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mobz/elasticsearch-head] Cluster health value: not connected (#438)





 
Do you see any errors, if you follow these steps: https://github.com/mobz/elasticsearch-head#running-with-built-in-server
