### ISSUE TITLE
How should I configure nginx proxy and elasticsearch-head (public network)

### ISSUE THREAD

**Issue by Teasnowy** [mobz/elasticsearch-head#469]
My PC cannot access the ES server directly

nginx.conf:
        location /head {
                add_header location "qufudcj.tpddns.cn:188/head";
                rewrite ^/head/(.*)$ /$1 break;
                sub_filter '_site' 'head/_site';
                sub_filter_types *;
                sub_filter_once off;
                proxy_pass http://192.168.0.161:9100/;
        }

however:
![image](https://user-images.githubusercontent.com/33077280/131272125-bebd2737-04ec-46c5-94a7-9d355bf81395.png)

**Comment by Teasnowy** [comment]
How to let "elasticsearch-head" access this IP by itself

**Comment by mobz** [comment]
elasticsearch-head does do any request routing. The request will be directly from the browser to your instance of elasticsearch. So it's not a matter of allowing elasticsearch-head to access elasticsearch, it's a matter of allowing the browser to access elasticsearch.
