### ISSUE TITLE
enable sort index by name descending

### ISSUE THREAD

**Issue by rtoma** [mobz/elasticsearch-head#59]
I am using ES for storing Logstash-created indexes, which are named using the "logstash-YYYY-MM-DD" format.

With the current sorting (by index name ascending) in Head, the most recent logstash index is shown on the most right.

Having lots of indexes, and almost always being interested in today's index, requires a lot of scrolling to the right.

![es-head-scrolling](https://f.cloud.github.com/assets/2914051/302273/32ff59ee-9601-11e2-8a5e-39f47dc122a1.PNG)

Maybe add a sort asc/desc option?

**Comment by japel** [comment]
👍

**Comment by philipskokoh** [comment]
#261

**Comment by philipskokoh** [comment]
related issue: #261

**Comment by Gmanweb** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by philipskokoh** [comment]
A feature to sort indices has been added in commit 3c18579. By default, the indices are sorted in descending order in favor rolling index practice. 
Please update the elasticsearch-head to latest version.
