### ISSUE TITLE
Feature Request: HTTP Authentication when accessing ElasticSearch

### ISSUE THREAD

**Issue by stoerr** [mobz/elasticsearch-head#72]
If you use ElasticSearch in production, you will need to protect access to the ElasticSearch API if it contains non public data. I guess this will usually be done with a firewall, but there are cases where simple HTTP authentication makes sense - for instance if you want to give developers / testers direct access by routing the API through an Apache and protecting the routed location. It would be nice if this was supported by elasticsearch-head.

**Comment by drush** [comment]
I concur with with @guptakaran11 that this is not working properly, at least in the current version of the plugin - possibly a regression.  I can replicate the behavior - headers are not being passed on requests in chrome at least.

**Comment by davetwofeetonthedirt** [comment]
Same issue for me.

**Comment by mtkage** [comment]
@davetwofeetonthedirt I ended up putting the ES instance on private VPC. The ES instance does not require auth and is not connected to the public network. It can be accessed via a reverse proxy (nginx in my case) that takes care of auth.
